# Install libraries (if needed)

In [1]:
"""
!pip install beir
!pip install fasttext
!pip install spacy
!pip scikit-learn
!pip install rank_bm25
"""

'\n!pip install beir\n!pip install fasttext\n!pip install spacy\n!pip scikit-learn\n!pip install rank_bm25\n'

# Import libraries

In [1]:
import pandas as pd

import beir 
from beir import util, LoggingHandler
from beir.datasets.data_loader import GenericDataLoader
from beir.retrieval.evaluation import EvaluateRetrieval

from utils_func import corpus_processing, matrix_creation, clustering, retriever_model, vector_creation

import os
import multiprocessing
multiprocessing.set_start_method("spawn", force=True)

import torch

from transformers import BertTokenizer, BertModel

c:\Users\maxim\anaconda3\envs\research_ir\Lib\site-packages\beir\util.py:2: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

# Run experiment

## Choose parameters

In [2]:
dataset = "arguana"                        # dataset you want to use, had to be available in the beir benchmark: https://github.com/beir-cellar/beir

use_ft = True                               # whether to use fasttext or not to handle unseen words
path_ft = 'cc.en.100.bin'                   # path to the fasttext model, if empty and use_ft is true, the model will be downloaded in the current directory
save_cleaned_corpus = ''                    # path to save the cleaned corpusn, if empty, the corpus will not be saved
save_scores = ''                            # path to save the scores, if empty, the scores will not be saved 

load_cleaned_corpus = ''                    # path to load the cleaned corpus, if empty, the corpus will be cleaned
load_vectors = f'word_vectors/word_vectors_{dataset}.csv' # path to load the word vectors, if empty, the vectors will be created
vector_dimension = 100                      # dimension of the word vectors
path_to_save_model = ''                     # path to save the fasttext model trained on the corpora, if empty, the model will not be saved

remove_original_corpus = False               # whether to remove the original corpus from the memory or not, to save memory

best_n_neighbors = 75                       # number of neighbors to consider to fill the similarity matrix
best_alpha = 0.76                           # alpha parameter, balancing the importance between similarity and coexistence
best_thresh = 0.75                          # threshold to consider a word as replaceable by another one
metric = 'cosine'                           # metric to use to compute the similarity matrix   
k1 = 1.5                                    # parameter of the BM25 algorithm 
b = 0.75                                    # parameter of the BM25 algorithm
thresh_prob=0.005                           # threshold to consider a value equals to 0 in the coexistence matrix           

knn_method = 'faiss'                        # method to use to compute the k-ne, either 'faiss' or 'exact'

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name, output_hidden_states=True).to(device)

## Run an experiment

In [4]:
url = "https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/{}.zip".format(dataset)
if not os.path.exists(f"datasets/"):
    os.makedirs(f"datasets/")
    
data_path = f"datasets/{dataset}"
corpus, queries, qrels = GenericDataLoader(data_folder=data_path).load(split="test")

100%|██████████| 8674/8674 [00:00<00:00, 162258.30it/s]

In [5]:
#queries['70'], corpus['4414547']

In [6]:
if load_cleaned_corpus == '':
    cleaned_corpus = corpus_processing.preprocess_corpus_dict(corpus)
    if save_cleaned_corpus != '':
        corpus_processing.save_processed_corpus(cleaned_corpus, save_cleaned_corpus)
else:
    cleaned_corpus = pd.read_csv(load_cleaned_corpus)
    cleaned_corpus = {cleaned_corpus['doc_id'][i]:cleaned_corpus['text'][i] for i in range(len(cleaned_corpus))}

if remove_original_corpus:
    corpus = None

Preprocessing corpus: 100%|██████████| 8674/8674 [00:44<00:00, 193.46it/s]

In [7]:
embeddings = vector_creation.create_vectors(cleaned_corpus, model, tokenizer, device)

c:\Users\maxim\anaconda3\envs\research_ir\Lib\site-packages\transformers\models\bert\modeling_bert.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Token indices sequence length is longer than the specified maximum sequence length for this model (576 > 512). Running this sequence through the model will result in indexing errors

In [8]:
cleaned_corpus = corpus_processing.preprocess_corpus_dict(corpus, tokenizer, True)

Preprocessing corpus: 100%|██████████| 8674/8674 [00:45<00:00, 188.59it/s]
Final processing: 100%|██████████| 8674/8674 [00:12<00:00, 702.94it/s]

In [9]:
'''
from sklearn.decomposition import PCA

idx_emb = list(embeddings.index)
pca = PCA(n_components=vector_dimension)
pca.fit(embeddings)
embeddings = pca.transform(embeddings)
embeddings = pd.DataFrame(embeddings, index=idx_emb)
model = None
'''

'\nfrom sklearn.decomposition import PCA\n\nidx_emb = list(embeddings.index)\npca = PCA(n_components=vector_dimension)\npca.fit(embeddings)\nembeddings = pca.transform(embeddings)\nembeddings = pd.DataFrame(embeddings, index=idx_emb)\nmodel = None\n'

In [10]:
scores = {}
best_alpha = 1.0
best_thresh = 0.85
retriever = retriever_model.UCFIRe(embeddings, None, tokenizer,n_neighbors = best_n_neighbors, alpha=best_alpha, thresh = best_thresh, metric = metric, k1 = k1, b = b, thresh_prob=thresh_prob)

retriever.fit(cleaned_corpus, is_clean=True, knn_method=knn_method)

retriever_okapi = EvaluateRetrieval(retriever, score_function="cos_sim") # or "dot" if you wish dot-product
results_okapi = retriever_okapi.retrieve(retriever.tokenized_corpus, queries)
# Evaluate the model (implement your own evaluation logic, e.g., compute mean reciprocal rank)
scores = retriever_okapi.evaluate(qrels, results_okapi, retriever_okapi.k_values)  # Replace this with your evaluation metric

if save_scores != '':
    with open(save_scores, 'w') as f:
        f.write(str(scores))
    
print(scores)

Getting unique words: 100%|██████████| 8674/8674 [00:00<00:00, 185192.28it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 16530/16530 [00:01<00:00, 9587.11it/s]
Getting replaceable words: 100%|██████████| 16530/16530 [00:02<00:00, 7118.07it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 13845/13845 [00:00<00:00, 1658151.93it/s]
100%|██████████| 8674/8674 [00:10<00:00, 840.86it/s]
tests in progress: 100%|██████████| 1406/1406 [05:03<00:00,  4.64it/s]

({'NDCG@1': 0.22191, 'NDCG@3': 0.34285, 'NDCG@5': 0.39515, 'NDCG@10': 0.44764, 'NDCG@100': 0.49856, 'NDCG@1000': 0.50346}, {'MAP@1': 0.22191, 'MAP@3': 0.31247, 'MAP@5': 0.34142, 'MAP@10': 0.36297, 'MAP@100': 0.37439, 'MAP@1000': 0.37457}, {'Recall@1': 0.22191, 'Recall@3': 0.43101, 'Recall@5': 0.55832, 'Recall@10': 0.72119, 'Recall@100': 0.94879, 'Recall@1000': 0.9872}, {'P@1': 0.22191, 'P@3': 0.14367, 'P@5': 0.11166, 'P@10': 0.07212, 'P@100': 0.00949, 'P@1000': 0.00099})

In [11]:
import numpy as np

clust_len = [len(retriever.clusters[i]) for i in range(len(retriever.clusters))]

In [12]:
max(clust_len), np.mean(clust_len), np.median(clust_len), np.std(clust_len)

(2020, 1.1939328277356447, 1.0, 17.181364866901625)

In [13]:
np.argmax(clust_len)#, retriever.clusters[np.argmax(clust_len)]

4

In [14]:
words_big_clust = list(retriever.clusters[np.argmax(clust_len)])
idx_big_clust = np.argmax(clust_len)

# initial replacement

word = words_big_clust[0]
retriever.clusters[idx_big_clust] = {word}

# other replacements
for word in words_big_clust[1:]:
    retriever.clusters.append({word})
    retriever.clust_dict[word] = len(retriever.clusters) - 1

In [15]:
new_clust_len = [len(retriever.clusters[i]) for i in range(len(retriever.clusters))]
max(new_clust_len), np.mean(new_clust_len), np.median(new_clust_len), np.std(new_clust_len)

(73, 1.041981845688351, 1.0, 0.8389638361571061)

In [16]:
retriever_okapi = EvaluateRetrieval(retriever, score_function="cos_sim") # or "dot" if you wish dot-product
results_okapi = retriever_okapi.retrieve(retriever.tokenized_corpus, queries)
# Evaluate the model (implement your own evaluation logic, e.g., compute mean reciprocal rank)
scores = retriever_okapi.evaluate(qrels, results_okapi, retriever_okapi.k_values)  # Replace this with your evaluation metric

if save_scores != '':
    with open(save_scores, 'w') as f:
        f.write(str(scores))
    
print(scores)

tests in progress: 100%|██████████| 1406/1406 [06:03<00:00,  3.87it/s]

({'NDCG@1': 0.22404, 'NDCG@3': 0.34418, 'NDCG@5': 0.39633, 'NDCG@10': 0.45024, 'NDCG@100': 0.49992, 'NDCG@1000': 0.50453}, {'MAP@1': 0.22404, 'MAP@3': 0.31401, 'MAP@5': 0.34278, 'MAP@10': 0.36481, 'MAP@100': 0.37591, 'MAP@1000': 0.3761}, {'Recall@1': 0.22404, 'Recall@3': 0.43172, 'Recall@5': 0.55903, 'Recall@10': 0.72688, 'Recall@100': 0.9495, 'Recall@1000': 0.98506}, {'P@1': 0.22404, 'P@3': 0.14391, 'P@5': 0.11181, 'P@10': 0.07269, 'P@100': 0.0095, 'P@1000': 0.00099})

In [17]:
scores

({'NDCG@1': 0.22404,
  'NDCG@3': 0.34418,
  'NDCG@5': 0.39633,
  'NDCG@10': 0.45024,
  'NDCG@100': 0.49992,
  'NDCG@1000': 0.50453},
 {'MAP@1': 0.22404,
  'MAP@3': 0.31401,
  'MAP@5': 0.34278,
  'MAP@10': 0.36481,
  'MAP@100': 0.37591,
  'MAP@1000': 0.3761},
 {'Recall@1': 0.22404,
  'Recall@3': 0.43172,
  'Recall@5': 0.55903,
  'Recall@10': 0.72688,
  'Recall@100': 0.9495,
  'Recall@1000': 0.98506},
 {'P@1': 0.22404,
  'P@3': 0.14391,
  'P@5': 0.11181,
  'P@10': 0.07269,
  'P@100': 0.0095,
  'P@1000': 0.00099})

In [12]:
retriever.clust_dict['new']

9287

In [15]:
retriever.clusters[6976], retriever.clusters[8052]

({'york'}, {'new'})

In [ ]:
list(retriever.rewritten_corpus.values())[0]

'6625 2498 4 10320 6084 8219 2558 8177 9188 8354 7468 4 8354 4 6625 2498 4 5607 390 2180 5870 277 10044 4 10320 6084 8835 10209 9461 8067 8107 4 277 4 3668 4 144 10320 6084 162 6625 2498 6653 5280 7545 8177 9188 10320 6084 3820 8354 8177 9188 4 260 8866 9771 6782 10320 6084 3820 7468 271 4 271 56 8016 1452 6032 4 7468 6084 4456 5585 6625 2498 4 9200 4 8697 3871 6374 4 8711 3254 3134 7591 671 4 277 6625 2498 6653 6625 2498 4 2883 1367 6404 2155 6418 8016 2 6362 4 6625 2498 4805 436 3764 8668 56 1696 9200 6988 4245 8668 449 4 9585 8668 4245 1696 6263 8016 449 8645 6362 1801 3764 8016 56 286 56 8668 7005 10320 6084 704 10136 7607 3303 2459 4445 54 9663 2523 9663 6625 2498 4 5098 555 144 10320 6084 162 7622 4245 8668 56 2778 2693 4245 8668 56 4 4245 8668 56 7622 4245 8668 56 2778 2693 4245 8668 56 4 4245 8668 56 3321 144 4 54 9663 6625 2498 4 4 438 388 8796 6395 6955 8313 1359 1801 6084 3820 8554 6835 2690 4255 6625 2498 4 2538 4 3088 1367 4 555 3088 4269 4778 4 3088 9873 2883 940 8219 8996 2523 9663 6625 2498 6653 4 3678 4185 8067 4 701 1710 1039 6183 6625 2498 8067 8219 10320 6084 3820'

In [ ]:
side_by_side = []
docs = []
for k, doc in enumerate(list(retriever.rewritten_corpus.values())):
    splitted = doc.split()

    for i in range(1, len(splitted)):
        word = splitted[i]
        word_bf = splitted[i-1]
        if word == word_bf:
            docs.append(k)
            side_by_side.append(word)

In [ ]:
uniques = set(side_by_side)
uniques = list(uniques)

In [ ]:
for clust in uniques:
    print(clust , retriever.clusters[int(clust)])

6039 {'water'}
144 {'risk'}
6259 {'coil'}
7193 {'chemical'}
7384 {'opium'}
145 {'surgery'}
2091 {'large', 'small'}
6418 {'4'}
681 {'bold'}
7607 {'tumor'}
8510 {'orange'}
2582 {'assessment', 'evaluation'}
7891 {'consultation'}
6378 {'work'}
5457 {'nut'}
5584 {'hospital'}
2384 {'nutrient'}
5197 {'obesity'}
6994 {'prick'}
355 {'i'}
5222 {'room'}
3988 {'e'}
1285 {'factor'}
8565 {'meal'}
8451 {'crop'}
2459 {'treatment', 'therapy'}
6185 {'adolescence', 'adulthood'}
5880 {'structure'}
5658 {'10'}
6661 {'good', 'excellent'}
177 {'16', '17', '23', '18', '15', '13', '22', '21', '19', '12', '14'}
4078 {'african'}
5536 {'catch'}
1455 {'gi'}
2308 {'effectively', 'successfully', 'efficiently', 'successful'}
3547 {'mushroom'}
9761 {'video'}
4324 {'uncertainty'}
7243 {'consumption'}
2353 {'smoking'}
4099 {'public'}
3241 {'status'}
4044 {'regulation', 'regulator'}
1666 {'compound'}
8 {'infection'}
8721 {'region', 'area'}
9588 {'vitamin'}
7731 {'v'}
5256 {'inhibitor'}
2538 {'association'}
5557 {'diet'}
3162 {'threshold'}
2618 {'aluminium', 'aluminum'}
5804 {'combine'}
5811 {'hopeless', 'worthless'}
5504 {'ms'}
2515 {'level'}
469 {'reliable', 'precise', 'exact', 'accurate'}
3889 {'hepatitis'}
7316 {'sample'}
8133 {'analysis'}
7497 {'extraction'}
5280 {'population'}
7449 {'homicide'}
2306 {'ct'}
6933 {'mechanism'}
2778 {'95'}
5589 {'oxygen'}
9183 {'cow'}
6734 {'preparation'}
2895 {'lifestyle'}
6056 {'match'}
2773 {'210'}
3211 {'consumer'}
8829 {'sensitive'}
6576 {'disk'}
9359 {'transfer'}
3231 {'metal'}
438 {'impact', 'influence', 'affect'}
6626 {'weight'}
286 {'##4', '##3', '##6', '##8', '##9', '##5', '##7'}
1654 {'anxiety'}
1405 {'incidence', 'prevalence'}
2700 {'event'}
6865 {'severe'}
3378 {'viewpoint', 'perspective'}
1468 {'annually', 'daily', 'monthly', 'yearly', 'weekly'}
8634 {'management'}
10057 {'network'}
1563 {'ft'}
2808 {'researcher', 'scientist', 'investigator', 'research'}
2014 {'blood'}
4245 {'0'}
3040 {'variability', 'variation', 'difference'}
555 {'high', 'low', 'higher', 'lower'}
5607 {'drug'}
8508 {'ol'}
4645 {'chicago'}
10178 {'cereal'}
5631 {'infant'}
5275 {'pork'}
407 {'fe'}
5093 {'antibody'}
10153 {'fruit'}
9278 {'vaccine'}
1561 {'canada', 'canadian'}
6910 {'score'}
1523 {'receive'}
2740 {'##y'}
9250 {'protein'}
10180 {'isolate'}
4814 {'vegetarian'}
7361 {'measurement', 'measure'}
6358 {'tuberculosis'}
4896 {'oyster'}
2460 {'child'}
8456 {'d'}
1244 {'physician'}
4706 {'platinum'}
7262 {'exercise'}
6138 {'aim'}
6843 {'family'}
343 {'people', 'person'}
971 {'cherry'}
2011 {'review'}
1347 {'eighteen', 'sixteen', 'thirteen', 'ninety', 'fourteen', 'thirty', 'seventy', 'nineteen', 'seven', 'eighty', 'seventeen'}
4374 {'trainee'}
4798 {'date'}
942 {'fat'}
2701 {'juice'}
1120 {'lifespan', 'longevity'}
71 {'program'}
10289 {'liquid'}
9011 {'energy'}
2121 {'normal'}
815 {'negative', 'positive'}
4345 {'result'}
2405 {'copper'}
3116 {'asthma'}
7397 {'common'}
4023 {'fish'}
1462 {'site'}
8953 {'purpose'}
1113 {'20'}
5802 {'l'}
5319 {'genetic'}
2883 {'time'}
1858 {'fiber'}
3502 {'human'}
2752 {'article'}
6678 {'india'}
6838 {'moderate'}
6718 {'tobacco'}
10136 {'age'}
7557 {'aix'}
1593 {'cell'}
9324 {'course'}
3426 {'report'}
8066 {'treat'}
9392 {'walnut'}
7424 {'additive'}
3303 {'characteristic'}
9641 {'vivo'}
8992 {'literature'}
5496 {'exposure'}
6084 {'cancer'}
9171 {'concentration'}
51 {'−'}
5640 {'arsenic'}
6362 {'participant'}
9585 {'9'}
7248 {'inflammation'}
8374 {'identification'}
6183 {'test', 'testing'}
4124 {'pr'}
7597 {'grape'}
5305 {'intervention'}
8735 {'constituent'}
3972 {'bean'}
5719 {'woman'}
3343 {'beverage', 'drink'}
6992 {'##q'}
1157 {'sao', 'paulo'}
10190 {'hormone'}
24 {'manufacturer', 'supplier'}
3267 {'>'}
435 {'world'}
1368 {'sugar'}
636 {'september', 'july', 'april', 'october', 'december', 'june', 'august', 'february', 'march', 'november', 'january'}
3088 {'dose'}
7716 {'metabolism'}
6507 {'chocolate'}
8607 {'nerve'}
1272 {'cis'}
6013 {'ec'}
994 {'intake'}
5757 {'record'}
1039 {'trial'}
8086 {'et'}
7782 {'hispanic'}
7005 {'2'}
5077 {'composition'}
8984 {'subject'}
547 {'black'}
3907 {'food'}
9410 {'coconut'}
3921 {'insulin'}
5455 {'different'}
4665 {'grade'}
3606 {'objective'}
3971 {'positively', 'negatively'}
8067 {'effect'}
2572 {'meaningful', 'significant', 'considerable', 'substantial'}
4322 {'taste'}
9764 {'present'}
2388 {'day'}
10124 {'dementia'}
8394 {'model'}
5431 {'body'}
7202 {'shift', 'change'}
1696 {'year'}
8354 {'study'}
9208 {'+'}
2165 {'individual'}
4729 {'occupation'}
6969 {'phase'}
5585 {'information'}
1284 {'fifth', 'fourth'}
1927 {'meat'}
5908 {'depression'}
4306 {'op'}
5814 {'mild'}
3678 {'possibility', 'possible', 'potential'}
9691 {'ala'}
10165 {'eye'}
5264 {'gain', 'loss'}
9596 {'cd'}
4209 {'temperature'}
6263 {'6'}
5426 {'head'}
1938 {'ss'}
9693 {'bad'}
6806 {'response', 'reaction'}
5352 {'g'}
1460 {'sweet'}
8576 {'evidence'}
6374 {'database'}
4056 {'popular', 'popularity'}
1502 {'restriction'}
2017 {'lc'}
1479 {'potato'}
833 {'ham'}
9873 {'-'}
6320 {'p'}
2063 {'accuracy', 'precision'}
3263 {'wine'}
8604 {'activity'}
7385 {'poultry', 'chicken'}
4661 {'kg'}
5935 {'7'}
1194 {'toxicity'}
1730 {'ed'}
296 {'rest'}
2417 {'gal'}
1016 {'cinnamon'}
292 {'indirectly', 'directly'}
5755 {'garlic'}
5090 {'indoor', 'outdoor'}
8404 {'1800', '1100'}
3820 {'patient'}
50 {'oil'}
9069 {'sudan'}
5000 {'spin'}
5922 {'kidney'}
7578 {'ratio'}
1477 {'ap'}
390 {'group'}
2064 {'twin'}
3279 {'efficient', 'effective'}
3811 {'rat'}
3466 {'month', 'week'}
8107 {'disease', 'illness'}
2996 {'##01', '##00'}
1596 {'tomato'}
5556 {'n'}
4259 {'cause'}
3508 {'plant'}
1748 {'agent'}
2087 {'old'}
2 {'144', '107', '160', '145', '700', '200', '172', '130', '300', '115', '153', '171', '122', '600', '188', '1000', '180', '155', '140', '190', '116', '114', '400', '113', '157', '133', '159', '500', '100', '150', '149', '170', '340', '126', '136', '147', '250', '109', '111', '108', '132', '151', '350', '168', '189', '121', '120', '103', '158', '900', '112', '127', '162', '187', '141', '143', '138', '148', '124', '128', '117', '123', '135', '118', '142', '106', '800', '105', '129', '134', '131', '139', '110', '156', '125', '173', '152', '174', '161', '104', '146', '119', '154', '137', '1200'}
4609 {'208', '207', '206'}
3955 {'cerebral'}
4011 {'system'}
178 {'face'}
7027 {'monitoring', 'surveillance'}
5283 {'thyroid'}
8589 {'man'}
271 {'2006', '1980', '1994', '1993', '1954', '1946', '1966', '1990', '1991', '2010', '1964', '1997', '1986', '1992', '2005', '1998', '1981', '2007', '2012', '1988', '1977', '2011', '1984', '1983', '1973', '1972', '1976', '1985', '2003', '2008', '1975', '2013', '2014', '1989', '2000', '1939', '1970', '2002', '1999', '1937', '2009', '1965', '2001', '1982', '1968', '1950', '1987', '1940', '1996', '1930', '1945', '1974', '1995', '2004'}
8627 {'w'}
6800 {'internal', 'external'}
5685 {'stress'}
1183 {'efficacy', 'effectiveness'}
8533 {'plate'}
3836 {'asbestos'}
2458 {'spice'}
7701 {'specimen'}
9000 {'product'}
1681 {'val'}
6032 {'case'}
6648 {'peak'}
2622 {'hair'}
9577 {'##to'}
5406 {'egg'}
2148 {'cycle'}
6247 {'tea'}
8309 {'##mo'}
719 {'arctic'}
9954 {'strawberry'}
4 {'perceive', 'argue', 'promote', 'inconsistent', 'compelling', 'manipulate', 'explain', 'improved', 'virtually', 'distinction', 'appreciate', 'evolve', 'consolidate', 'manage', 'occasionally', 'arise', 'commonly', 'abandon', 'gives', 'largely', 'reportedly', 'depend', 'seek', 'compose', 'estimate', 'lately', 'conclusion', 'gradually', 'implement', 'include', 'briefly', 'stimulate', 'obscure', 'disturb', 'discussion', 'lend', 'conserve', 'involve', 'interested', 'commonplace', 'inferno', 'cooperate', 'advocate', 'unlikely', 'comment', 'preserve', 'multitude', 'rapid', 'justify', 'suggest', 'cloak', 'steadily', 'occur', 'subsequent', 'agree', 'particularly', 'completely', 'subsequently', 'enhance', 'reject', 'notable', 'impossible', 'examine', 'remarkably', 'diminished', 'distribute', 'believe', 'apparently', 'extensively', 'highlight', 'finally', 'difficult', 'emphasize', 'enforce', 'worried', 'represent', 'aside', 'persuade', 'address', 'correspond', 'deliver', 'expand', 'operate', 'previous', 'reduction', 'demonstrate', 'designate', 'develop', 'emerge', 'likely', 'initiate', 'recently', 'compute', 'implementation', 'depict', 'conduct', 'disclose', 'totally', 'collection', 'concept', 'determine', 'adopt', 'appear', 'bring', 'vary', 'determination', 'markedly', 'formidable', 'calculate', 'propose', 'attempt', 'attend', 'belong', 'destroy', 'eliminate', 'convince', 'presence', 'usage', 'uphold', 'accordingly', 'weaken', 'debate', 'regard', 'intriguing', 'continue', 'prevent', 'particular', 'persist', 'vanish', 'render', 'primarily', 'interceptor', 'proceed', 'undermine', 'impose', 'imply', 'chiefly', 'prominent', 'suggestion', 'essentially', 'verify', 'disappear', 'indicate', 'favour', 'supposedly', 'encourage', 'respect', '1824', 'lush', 'discreet', 'theoretically', 'consideration', 'discuss', 'assess', 'usually', 'allow', 'removal', 'coincide', 'pedro', 'offer', 'intervene', 'employ', 'encouraging', 'ultimately', 'entertain', 'concerned', 'posse', 'frequently', 'generally', 'controversial', 'consequently', 'unexpected', 'predominantly', 'intersection', 'introduction', 'installment', 'comprise', 'creation', 'slow', 'taxis', 'assume', 'lay', 'participate', 'potentially', 'notion', 'rise', 'evidently', 'perform', 'exploration', 'enjoy', 'relate', 'unable', 'possibly', 'constantly', 'strengthen', 'arguably', 'explanation', 'confirm', '–', 'determined', 'accompany', 'choose', 'claim', 'underway', 'evaluate', 'display', '‑', 'settle', 'fully', 'estimation', 'generate', 'enable', 'possess', 'systematically', 'increase', 'identify', 'slowly', 'seemingly', 'originally', 'seldom', 'characterized', 'unnoticed', 'realize', 'quickly', 'consist', 'interesting', 'rely', 'rarely', 'consistent', 'inability', 'begin', 'remain', 'acknowledge', 'undertake', 'suggested', 'principally', 'nonetheless', 'organise', 'obtain', 'reach', 'denomination', 'consider', 'widely', 'existence', 'start', 'analogous', 'greatly', '‐', 'distinguish', 'controversy', 'convincing', 'shepherd', 'assumption', 'collect', 'discovery', 'routinely', 'substantially', 'effort', 'kill', 'urge', 'clearly', 'rapidly', 'confused', 'assure', 'introduce', 'ignore', 'hopefully', 'discourage', 'resist', 'probably', 'favor', 'fortunately', 'overlook', 'understanding', 'speculation', 'conflicting', 'unexpectedly', 'decide', 'send', 'reveal', 'apply', 'differ', 'gather', 'recognise', 'elevated', 'achieve', 'significantly', 'reconcile', 'typically', 'emergence', 'able', 'hardly', 'know', 'investigate', 'ironically', 'extend', 'select', 'considerably', 'desirable', 'surprising', 'discover', 'prove', 'decrease', 'disperse', 'satisfy', 'relieve', 'surprisingly', 'varied', 'utilize', 'differentiate', 'regularly', 'reassure', 'activate', 'finding', 'outline', 'pursue', 'reinforce', 'undoubtedly', 'recent', 'originate', 'use', 'exclusively', 'inform', 'reduce', 'enhanced', 'conclude', 'actually', 'build', 'noteworthy', 'owe', 'exploit', 'happen', 'provide', 'await', 'calculation', 'accomplish', 'reside', 'uncover', 'historically', 'mainly', 'obviously', 'disappearance', 'improve', 'create', 'eventually', 'disregard', 'lastly', 'normally', 'drastically', 'facilitate', 'clarify', 'understand', 'practically', 'inhibit', 'initially', 'confuse', 'educate', 'especially', 'produce', 'constitute', 'observe', 'describe', 'decline', 'confront', 'explore', 'incorporate', 'admit', 'invariably', 'numerous', 'described', 'analyze', 'require', 'dramatically', 'worthy', 'retain', 'illustrate', 'integrate', 'necessarily', 'contain', 'induce', 'presumably', 'increased', 'unusual', 'maintain', 'elusive', 'dozen', 'recommend', 'permit', 'establish', 'solely', 'exhibit', 'prosperous', 'pointer', 'known', 'established', 'specifically', '1648', 'capable', 'minimize', 'mandate', 'locate', 'reduced', 'avoid', 'milton', 'traditionally', 'profoundly', 'recommendation', 'remove', 'explode', 'globe', 'consistently', 'govern', 'continually', 'need', 'widespread', 'contradictory', 'define', 'repeatedly', 'specify', 'recognize', 'pose', 'acquire', 'halt', 'deserve', 'prediction', 'continued', 'alleviate', 'advise', 'find', 'remarkable', 'dispute', 'intend', 'come', 'exist', 'entirely', 'think', 'dismiss', 'strongly', 'previously', 'devote', 'dreadful', 'reflect', 'accumulate', 'specific', 'maximize'}
4891 {'se'}
5157 {'weak', 'strong'}
6053 {'panel'}
8871 {'arterial'}
8355 {'nk'}
3753 {'boil'}
5834 {'h'}
9048 {'contact'}
4767 {'cage'}
8826 {'outside', 'inside'}
1727 {'pop'}
9686 {'gene'}
4295 {'type'}
6827 {'cluster'}
7913 {'plasma'}
5568 {'health'}
1291 {'afternoon', 'evening', 'morning'}
6413 {'jun'}
8429 {'}'}
1091 {'female', 'male'}
3856 {'5'}
2585 {'rate'}
8889 {'milk'}
7230 {'asia', 'asian'}
2144 {'injury', 'damage'}
5308 {'grain'}
8764 {'pregnancy'}
9969 {'state'}
671 {'method', 'methodology', 'procedure', 'technique'}
5340 {'vol'}
7522 {'animal'}
2632 {'label'}
5566 {'apple'}
2326 {'salmon'}
3114 {'liver'}
1524 {'cooking'}
4006 {'cat'}
5613 {'value'}
7199 {'adolescent'}
3186 {'1'}
3764 {'3'}
3119 {'ad'}
6569 {'italy', 'italian'}
8837 {'gut'}
7705 {'peanut'}
6208 {'f'}
56 {'44', '88', '80', '92', '39', '28', '48', '87', '74', '91', '47', '53', '45', '27', '38', '60', '94', '73', '79', '75', '84', '70', '54', '36', '49', '77', '59', '37', '26', '42', '34', '41', '78', '32', '35', '58', '31', '46', '97', '63', '50', '43', '93', '99', '96', '68', '61', '56', '64', '71', '82', '81', '85', '86', '98', '62', '40', '55', '51', '72', '29', '67', '76', '69', '90', '52', '57', '83', '66', '25', '89', '33', '65'}
3296 {'iron'}
169 {'vegetable'}
2021 {'http', 'www'}
1041 {'iq'}
4269 {'long', 'short'}
6133 {'cost'}

In [1]:
test = {'perceive', 'argue', 'promote', 'inconsistent', 'compelling', 'manipulate', 'explain', 'improved', 'virtually', 'distinction', 'appreciate', 'evolve', 'consolidate', 'manage', 'occasionally', 'arise', 'commonly', 'abandon', 'gives', 'largely', 'reportedly', 'depend', 'seek', 'compose', 'estimate', 'lately', 'conclusion', 'gradually', 'implement', 'include', 'briefly', 'stimulate', 'obscure', 'disturb', 'discussion', 'lend', 'conserve', 'involve', 'interested', 'commonplace', 'inferno', 'cooperate', 'advocate', 'unlikely', 'comment', 'preserve', 'multitude', 'rapid', 'justify', 'suggest', 'cloak', 'steadily', 'occur', 'subsequent', 'agree', 'particularly', 'completely', 'subsequently', 'enhance', 'reject', 'notable', 'impossible', 'examine', 'remarkably', 'diminished', 'distribute', 'believe', 'apparently', 'extensively', 'highlight', 'finally', 'difficult', 'emphasize', 'enforce', 'worried', 'represent', 'aside', 'persuade', 'address', 'correspond', 'deliver', 'expand', 'operate', 'previous', 'reduction', 'demonstrate', 'designate', 'develop', 'emerge', 'likely', 'initiate', 'recently', 'compute', 'implementation', 'depict', 'conduct', 'disclose', 'totally', 'collection', 'concept', 'determine', 'adopt', 'appear', 'bring', 'vary', 'determination', 'markedly', 'formidable', 'calculate', 'propose', 'attempt', 'attend', 'belong', 'destroy', 'eliminate', 'convince', 'presence', 'usage', 'uphold', 'accordingly', 'weaken', 'debate', 'regard', 'intriguing', 'continue', 'prevent', 'particular', 'persist', 'vanish', 'render', 'primarily', 'interceptor', 'proceed', 'undermine', 'impose', 'imply', 'chiefly', 'prominent', 'suggestion', 'essentially', 'verify', 'disappear', 'indicate', 'favour', 'supposedly', 'encourage', 'respect', '1824', 'lush', 'discreet', 'theoretically', 'consideration', 'discuss', 'assess', 'usually', 'allow', 'removal', 'coincide', 'pedro', 'offer', 'intervene', 'employ', 'encouraging', 'ultimately', 'entertain', 'concerned', 'posse', 'frequently', 'generally', 'controversial', 'consequently', 'unexpected', 'predominantly', 'intersection', 'introduction', 'installment', 'comprise', 'creation', 'slow', 'taxis', 'assume', 'lay', 'participate', 'potentially', 'notion', 'rise', 'evidently', 'perform', 'exploration', 'enjoy', 'relate', 'unable', 'possibly', 'constantly', 'strengthen', 'arguably', 'explanation', 'confirm', '–', 'determined', 'accompany', 'choose', 'claim', 'underway', 'evaluate', 'display', '‑', 'settle', 'fully', 'estimation', 'generate', 'enable', 'possess', 'systematically', 'increase', 'identify', 'slowly', 'seemingly', 'originally', 'seldom', 'characterized', 'unnoticed', 'realize', 'quickly', 'consist', 'interesting', 'rely', 'rarely', 'consistent', 'inability', 'begin', 'remain', 'acknowledge', 'undertake', 'suggested', 'principally', 'nonetheless', 'organise', 'obtain', 'reach', 'denomination', 'consider', 'widely', 'existence', 'start', 'analogous', 'greatly', '‐', 'distinguish', 'controversy', 'convincing', 'shepherd', 'assumption', 'collect', 'discovery', 'routinely', 'substantially', 'effort', 'kill', 'urge', 'clearly', 'rapidly', 'confused', 'assure', 'introduce', 'ignore', 'hopefully', 'discourage', 'resist', 'probably', 'favor', 'fortunately', 'overlook', 'understanding', 'speculation', 'conflicting', 'unexpectedly', 'decide', 'send', 'reveal', 'apply', 'differ', 'gather', 'recognise', 'elevated', 'achieve', 'significantly', 'reconcile', 'typically', 'emergence', 'able', 'hardly', 'know', 'investigate', 'ironically', 'extend', 'select', 'considerably', 'desirable', 'surprising', 'discover', 'prove', 'decrease', 'disperse', 'satisfy', 'relieve', 'surprisingly', 'varied', 'utilize', 'differentiate', 'regularly', 'reassure', 'activate', 'finding', 'outline', 'pursue', 'reinforce', 'undoubtedly', 'recent', 'originate', 'use', 'exclusively', 'inform', 'reduce', 'enhanced', 'conclude', 'actually', 'build', 'noteworthy', 'owe', 'exploit', 'happen', 'provide', 'await', 'calculation', 'accomplish', 'reside', 'uncover', 'historically', 'mainly', 'obviously', 'disappearance', 'improve', 'create', 'eventually', 'disregard', 'lastly', 'normally', 'drastically', 'facilitate', 'clarify', 'understand', 'practically', 'inhibit', 'initially', 'confuse', 'educate', 'especially', 'produce', 'constitute', 'observe', 'describe', 'decline', 'confront', 'explore', 'incorporate', 'admit', 'invariably', 'numerous', 'described', 'analyze', 'require', 'dramatically', 'worthy', 'retain', 'illustrate', 'integrate', 'necessarily', 'contain', 'induce', 'presumably', 'increased', 'unusual', 'maintain', 'elusive', 'dozen', 'recommend', 'permit', 'establish', 'solely', 'exhibit', 'prosperous', 'pointer', 'known', 'established', 'specifically', '1648', 'capable', 'minimize', 'mandate', 'locate', 'reduced', 'avoid', 'milton', 'traditionally', 'profoundly', 'recommendation', 'remove', 'explode', 'globe', 'consistently', 'govern', 'continually', 'need', 'widespread', 'contradictory', 'define', 'repeatedly', 'specify', 'recognize', 'pose', 'acquire', 'halt', 'deserve', 'prediction', 'continued', 'alleviate', 'advise', 'find', 'remarkable', 'dispute', 'intend', 'come', 'exist', 'entirely', 'think', 'dismiss', 'strongly', 'previously', 'devote', 'dreadful', 'reflect', 'accumulate', 'specific', 'maximize'}

In [2]:
len(test)

445

In [17]:
retriever.replaceable_words["entirely"]

{'completely', 'entirely', 'exclusively', 'totally'}

In [ ]:
for clust in retriever.clusters:
    if len(clust) > 1:
        print(clust)

{'favour', 'speculation', 'contradictory', 'dismiss', 'consider', 'hopefully', 'apply', 'encouraging', 'existence', 'remarkably', 'seemingly', 'urge', 'decline', 'resist', 'entirely', 'manage', 'proceed', 'clarify', 'arise', 'frequently', 'advise', 'recommend', 'repeatedly', 'clearly', 'differ', 'discreet', 'overlook', 'substantially', 'rarely', 'profoundly', 'worried', 'discover', 'remarkable', 'use', 'gives', 'virtually', 'remove', 'briefly', 'bring', 'formidable', 'compute', 'address', 'introduce', 'slow', 'enable', 'build', 'display', 'gradually', 'appreciate', 'essentially', 'extensively', 'mainly', 'acquire', 'unusual', 'inferno', 'analyze', 'await', 'inconsistent', 'collection', 'require', 'evaluate', 'settle', 'previous', 'intend', 'able', 'owe', 'accumulate', 'believe', 'varied', 'disappearance', 'reach', 'increase', 'occasionally', 'actually', 'suggested', 'accordingly', 'decrease', 'interested', 'solely', 'supposedly', 'establish', 'lay', 'normally', 'comment', 'creation', 'convincing', 'interceptor', 'consideration', 'posse', 'compose', 'assure', 'acknowledge', 'ultimately', 'multitude', 'regularly', 'assume', 'obtain', 'disclose', 'cloak', 'satisfy', 'surprising', 'practically', 'relieve', 'completely', 'decide', 'theoretically', 'impossible', 'prosperous', 'shepherd', 'realize', 'consist', 'strengthen', 'attend', 'slowly', 'produce', 'nonetheless', 'permit', 'depict', 'specifically', 'particularly', 'exhibit', 'ignore', 'justify', 'uphold', 'designate', 'specify', 'govern', 'conflicting', 'suggestion', 'prediction', 'confused', 'likely', 'undermine', 'capable', 'greatly', 'lush', 'interesting', 'desirable', 'probably', 'eventually', 'routinely', 'begin', 'regard', 'numerous', 'remain', 'notable', 'markedly', 'enhance', 'recently', 'alleviate', 'examine', 'obviously', 'suggest', 'exclusively', 'widespread', 'perceive', 'vary', 'particular', 'calculation', 'pose', 'create', 'underway', 'enjoy', 'obscure', 'confuse', 'distribute', 'develop', 'reveal', 'destroy', 'notion', 'enforce', 'estimation', 'come', '–', 'fully', 'mandate', 'relate', 'organise', 'participate', 'evidently', 'prevent', 'steadily', 'constitute', 'attempt', 'originate', 'vanish', 'concept', 'enhanced', 'reportedly', 'widely', 'happen', 'determined', 'diminished', 'educate', 'rapidly', 'confront', 'accomplish', 'adopt', 'identify', 'dispute', 'claim', 'deliver', 'respect', 'continually', 'persist', 'explain', 'convince', 'inhibit', 'pedro', 'usually', 'continued', 'initiate', 'send', 'promote', 'demonstrate', 'lend', 'determination', 'rise', 'persuade', 'presumably', 'undertake', 'implement', 'unlikely', 'typically', 'understanding', 'predominantly', 'investigate', 'discuss', 'appear', 'avoid', 'think', 'assess', 'highlight', 'weaken', 'disregard', 'strongly', 'accompany', 'discovery', 'unexpectedly', 'kill', 'traditionally', 'globe', 'lately', 'conserve', 'considerably', 'dreadful', 'specific', 'gather', 'inform', 'intriguing', 'reflect', 'manipulate', 'impose', 'totally', 'surprisingly', '‑', 'conduct', 'consistent', 'discussion', 'entertain', 'milton', 'argue', 'subsequently', 'prominent', 'undoubtedly', 'conclude', 'debate', 'distinguish', 'worthy', 'include', 'drastically', 'disperse', 'recognise', 'allow', 'introduction', 'possibly', 'preserve', 'offer', 'quickly', 'confirm', 'conclusion', 'collect', 'reduce', 'removal', 'consistently', 'distinction', 'previously', 'reduced', 'disappear', 'integrate', 'observe', 'estimate', 'propose', 'potentially', 'minimize', 'explode', 'halt', 'reinforce', 'usage', 'increased', 'invariably', 'involve', 'advocate', 'unable', 'reside', 'described', 'finding', 'primarily', 'improve', 'verify', 'recommendation', 'reassure', 'seldom', 'concerned', 'finally', 'exploration', 'arguably', 'coincide', 'determine', 'improved', '‐', 'rely', 'commonly', 'compelling', 'agree', 'eliminate', 'inability', 'incorporate', 'difficult', 'facilitate', 'subsequent', 'denomination', 'consolidate', 'emergence', 'comprise', 'select', 'explore', 'chiefly', 'depend', 'activate', 'operate', 'prove', 'exploit', 'belong', 'unnoticed', 'largely', 'occur', 'favor', 'rapid', 'exist', 'established', 'ironically', 'define', 'hardly', 'significantly', 'find', 'generally', '1648', 'characterized', 'taxis', 'represent', 'choose', 'especially', 'lastly', 'explanation', 'imply', 'elusive', 'possess', 'dramatically', 'installment', 'provide', 'understand', 'induce', 'locate', 'commonplace', 'extend', 'seek', 'historically', 'outline', 'principally', 'constantly', 'effort', 'deserve', 'reconcile', 'employ', 'systematically', 'reduction', 'intervene', 'originally', 'devote', 'recent', 'achieve', 'indicate', 'apparently', 'continue', 'dozen', 'pointer', 'admit', 'illustrate', 'intersection', 'emerge', 'noteworthy', 'disturb', 'correspond', 'necessarily', 'known', 'perform', 'encourage', 'unexpected', 'generate', 'consequently', 'evolve', 'uncover', 'render', 'discourage', 'contain', 'calculate', 'controversy', 'initially', 'need', 'presence', 'stimulate', 'know', 'implementation', 'emphasize', 'assumption', 'cooperate', 'reject', 'describe', 'fortunately', 'differentiate', 'retain', 'start', 'analogous', 'maintain', 'pursue', 'elevated', 'aside', 'maximize', 'expand', 'abandon', '1824', 'recognize', 'controversial', 'utilize'}
{'1986', '1997', '2003', '2001', '1989', '1965', '1983', '2005', '1993', '1982', '1980', '1998', '2008', '1994', '1992', '1981', '1945', '2010', '1940', '2011', '1954', '2006', '1976', '1977', '1991', '1964', '2002', '2004', '1999', '2007', '1988', '1984', '1946', '1974', '1975', '1985', '2000', '2012', '1990', '1972', '2009', '1966', '1987', '1968', '1930', '2013', '1996', '2014', '1995', '1970', '1973', '1937', '1950', '1939'}
{'despite', 'spite'}
{'investigator', 'research', 'researcher', 'scientist'}
{'3000', '5000'}
{'268', '269', '267'}
{'##3', '##8', '##9', '##5', '##7', '##4', '##6'}
{'297', '276', '295', '290', '275'}
{'german', 'germany'}
{'71', '73', '45', '83', '64', '31', '61', '80', '25', '77', '41', '36', '34', '93', '85', '69', '49', '91', '59', '42', '40', '46', '76', '58', '37', '33', '98', '55', '88', '90', '70', '54', '97', '67', '82', '96', '94', '74', '26', '79', '87', '99', '57', '48', '75', '27', '35', '89', '68', '78', '44', '92', '38', '65', '28', '81', '84', '72', '51', '53', '50', '29', '66', '32', '63', '43', '56', '52', '39', '47', '86', '62', '60'}
{'education', 'educational'}
{'exact', 'precise', 'accurate', 'reliable'}
{'eighteen', 'seventeen', 'fourteen', 'nineteen', 'ninety', 'thirty', 'seventy', 'eighty', 'thirteen', 'seven', 'sixteen'}
{'125', '173', '159', '118', '161', '162', '188', '137', '107', '132', '111', '142', '120', '117', '150', '140', '134', '340', '174', '900', '127', '122', '158', '139', '190', '130', '143', '149', '114', '152', '144', '1200', '105', '103', '189', '171', '148', '108', '116', '128', '700', '110', '133', '250', '170', '500', '160', '600', '119', '180', '126', '129', '300', '124', '113', '104', '154', '350', '147', '145', '187', '106', '109', '123', '400', '131', '168', '115', '153', '800', '200', '138', '146', '155', '172', '121', '156', '151', '112', '100', '157', '141', '136', '135', '1000'}
{'importance', 'relevance', 'significance'}
{'damage', 'injury'}
{'variation', 'difference', 'variability'}
{'sao', 'paulo'}
{'test', 'testing'}
{'##ological', '##logic', '##logical'}
{'december', 'july', 'june', 'january', 'september', 'april', 'october', 'november', 'august', 'february', 'march'}
{'fifth', 'fourth'}
{'outdoor', 'indoor'}
{'cattle', 'livestock'}
{'korean', 'korea'}
{'person', 'people'}
{'therapy', 'treatment'}
{'##maker', 'maker'}
{'1800', '1100'}
{'signaling', 'signalling'}
{'##ration', '##ization', '##tion', '##ation'}
{'220', '215', '217', '216'}
{'weak', 'strong'}
{'intention', 'intent'}
{'european', 'europe'}
{'distinctive', 'distinct'}
{'effective', 'efficient'}
{'##ted', '##zed', '##ed', '##ated'}
{'viewpoint', 'perspective'}
{'example', 'instance'}
{'crucial', 'helpful', 'important', 'useful', 'valuable', 'key'}
{'probability', 'likelihood'}
{'convert', 'conversion'}
{'feeling', 'feel'}
{'monthly', 'weekly', 'yearly', 'daily', 'annually'}
{'consume', 'eat'}
{'insufficient', 'inadequate'}
{'adequate', 'sufficiently', 'sufficient'}
{'##35', '##39', '##34', '##44', '##37'}
{'232', '229', '234', '233'}
{'##ise', '##ize'}
{'separately', 'separate', 'independently'}
{'##ically', '##ally'}
{'safely', 'properly', 'correctly', 'accurately', 'adequately'}
{'sparse', 'scarce'}
{'271', '272'}
{'limitation', 'limit'}
{'reasonably', 'reasonable'}
{'appropriate', 'suitable'}
{'successful', 'successfully', 'effectively', 'efficiently'}
{'assessment', 'evaluation'}
{'relatively', 'comparatively'}
{'concurrently', 'concurrent', 'simultaneously'}
{'procedure', 'methodology', 'technique', 'method'}
{'evan', 'ritchie'}
{'centre', 'center'}
{'tremendous', 'huge', 'impressive', 'immense', 'enormous'}
{'wealthy', 'affluent'}
{'experience', 'encounter'}
{'agriculture', 'agricultural'}
{'253', '252'}
{'dutch', 'netherlands'}
{'chicken', 'poultry'}
{'examination', 'exam'}
{'disruption', 'disturbance'}
{'326', '327', '325', '324'}
{'vulnerable', 'susceptible'}
{'02', '07', '03', '06', '01', '04', '08', '09', '05'}
{'detect', 'detection'}
{'furthermore', 'additionally'}
{'significant', 'substantial', 'meaningful', 'considerable'}
{'negatively', 'positively'}
{'##ible', '##able'}
{'308', '307'}
{'lower', 'high', 'higher', 'low'}
{'gain', 'loss'}
{'functioning', 'function'}
{'modern', 'contemporary'}
{'interpret', 'interpretation'}
{'popular', 'popularity'}
{'202', '204', '203'}
{'morning', 'evening', 'afternoon'}
{'207', '206', '208'}
{'emphasis', 'focus'}
{'166', '167', '169'}
{'##zhou', '##yang'}
{'shift', 'change'}
{'interference', 'interfere'}
{'prevalence', 'incidence'}
{'12', '21', '22', '14', '16', '23', '17', '15', '18', '13', '19'}
{'evident', 'obvious', 'apparent'}
{'possibility', 'potential', 'possible'}
{'comparison', 'compare'}
{'detrimental', 'dangerous', 'harmful'}
{'broad', 'wide'}
{'excellent', 'good'}
{'absence', 'absent'}
{'danger', 'threat'}
{'short', 'long'}
{'currently', 'presently'}
{'relation', 'relationship'}
{'favourable', 'favorable'}
{'effectiveness', 'efficacy'}
{'link', 'connection'}
{'asian', 'asia'}
{'italian', 'italy'}
{'external', 'internal'}
{'chinese', 'china'}
{'hopeless', 'worthless'}
{'adjusted', 'adjust', 'adjustment'}
{'disease', 'illness'}
{'miserable', 'sad'}
{'authority', 'agency'}
{'feasible', 'plausible'}
{'norwegian', 'norway'}
{'upward', 'downward'}
{'purchase', 'sell', 'buy', 'sale'}
{'192', '194', '196', '195'}
{'importantly', 'notably'}
{'minimum', 'maximum'}
{'338', '339'}
{'##inate', '##inated'}
{'taiwanese', 'taiwan'}
{'easily', 'readily', 'easy'}
{'##ology', '##logy'}
{'##logist', '##ologist'}
{'214', '213'}
{'##r', '##er'}
{'nowadays', 'today'}
{'##lin', '##ne', '##n', '##in', '##rin', '##ine'}
{'modify', 'alter'}
{'##ity', '##ness'}
{'measure', 'measurement'}
{'monitoring', 'surveillance'}
{'alteration', 'modification'}
{'observed', 'measured', 'calculated'}
{'256', '255', '257', '258'}
{'www', 'http'}
{'sweden', 'swedish'}
{'precision', 'accuracy'}
{'microscopy', 'microscope'}
{'670', '680', '620'}
{'area', 'region'}
{'##00', '##01'}
{'simulate', 'simulated'}
{'regulator', 'regulation'}
{'registry', 'register'}
{'beverage', 'drink'}
{'inexpensive', 'affordable'}
{'outside', 'inside'}
{'prevalent', 'predominant', 'dominant'}
{'indirectly', 'directly'}
{'similarly', 'likewise', 'similar', 'comparable'}
{'##te', '##ate'}
{'177', '179'}
{'epidemic', 'outbreak'}
{'manufacturer', 'supplier'}
{'adulthood', 'adolescence'}
{'unknown', 'uncertain', 'unclear'}
{'shop', 'store'}
{'bacteria', 'bacterium', 'bacterial'}
{'modeling', 'modelling'}
{'278', '277'}
{'304', '303', '305'}
{'japanese', 'japan'}
{'exceptionally', 'extremely'}
{'restoration', 'restore'}
{'negative', 'positive'}
{'longevity', 'lifespan'}
{'small', 'large'}
{'daytime', 'nighttime'}
{'organisation', 'organization'}
{'scottish', 'scotland'}
{'response', 'reaction'}
{'carefully', 'careful'}
{'102', '101'}
{'influence', 'impact', 'affect'}
{'zhang', 'cheng'}
{'##ing', '##ling', '##ting'}
{'danish', 'denmark'}
{'geographic', 'geographical'}
{'capability', 'ability'}
{'alternative', 'alternate'}
{'dependency', 'dependence'}
{'aluminium', 'aluminum'}
{'##rize', '##rise'}
{'canada', 'canadian'}
{'finland', 'finnish'}
{'staff', 'personnel'}
{'publish', 'publication'}
{'worldwide', 'globally'}
{'570', '580'}
{'slight', 'slightly', 'somewhat'}
{'##uary', 'police'}
{'male', 'female'}
{'defence', 'defense'}
{'australian', 'australia'}
{'partially', 'partly'}
{'hd', 'ld'}
{'week', 'month'}

In [18]:
words = list({'favour', 'speculation', 'contradictory', 'dismiss', 'consider', 'hopefully', 'apply', 'encouraging', 'existence', 'remarkably', 'seemingly', 'urge', 'decline', 'resist', 'entirely', 'manage', 'proceed', 'clarify', 'arise', 'frequently', 'advise', 'recommend', 'repeatedly', 'clearly', 'differ', 'discreet', 'overlook', 'substantially', 'rarely', 'profoundly', 'worried', 'discover', 'remarkable', 'use', 'gives', 'virtually', 'remove', 'briefly', 'bring', 'formidable', 'compute', 'address', 'introduce', 'slow', 'enable', 'build', 'display', 'gradually', 'appreciate', 'essentially', 'extensively', 'mainly', 'acquire', 'unusual', 'inferno', 'analyze', 'await', 'inconsistent', 'collection', 'require', 'evaluate', 'settle', 'previous', 'intend', 'able', 'owe', 'accumulate', 'believe', 'varied', 'disappearance', 'reach', 'increase', 'occasionally', 'actually', 'suggested', 'accordingly', 'decrease', 'interested', 'solely', 'supposedly', 'establish', 'lay', 'normally', 'comment', 'creation', 'convincing', 'interceptor', 'consideration', 'posse', 'compose', 'assure', 'acknowledge', 'ultimately', 'multitude', 'regularly', 'assume', 'obtain', 'disclose', 'cloak', 'satisfy', 'surprising', 'practically', 'relieve', 'completely', 'decide', 'theoretically', 'impossible', 'prosperous', 'shepherd', 'realize', 'consist', 'strengthen', 'attend', 'slowly', 'produce', 'nonetheless', 'permit', 'depict', 'specifically', 'particularly', 'exhibit', 'ignore', 'justify', 'uphold', 'designate', 'specify', 'govern', 'conflicting', 'suggestion', 'prediction', 'confused', 'likely', 'undermine', 'capable', 'greatly', 'lush', 'interesting', 'desirable', 'probably', 'eventually', 'routinely', 'begin', 'regard', 'numerous', 'remain', 'notable', 'markedly', 'enhance', 'recently', 'alleviate', 'examine', 'obviously', 'suggest', 'exclusively', 'widespread', 'perceive', 'vary', 'particular', 'calculation', 'pose', 'create', 'underway', 'enjoy', 'obscure', 'confuse', 'distribute', 'develop', 'reveal', 'destroy', 'notion', 'enforce', 'estimation', 'come', '–', 'fully', 'mandate', 'relate', 'organise', 'participate', 'evidently', 'prevent', 'steadily', 'constitute', 'attempt', 'originate', 'vanish', 'concept', 'enhanced', 'reportedly', 'widely', 'happen', 'determined', 'diminished', 'educate', 'rapidly', 'confront', 'accomplish', 'adopt', 'identify', 'dispute', 'claim', 'deliver', 'respect', 'continually', 'persist', 'explain', 'convince', 'inhibit', 'pedro', 'usually', 'continued', 'initiate', 'send', 'promote', 'demonstrate', 'lend', 'determination', 'rise', 'persuade', 'presumably', 'undertake', 'implement', 'unlikely', 'typically', 'understanding', 'predominantly', 'investigate', 'discuss', 'appear', 'avoid', 'think', 'assess', 'highlight', 'weaken', 'disregard', 'strongly', 'accompany', 'discovery', 'unexpectedly', 'kill', 'traditionally', 'globe', 'lately', 'conserve', 'considerably', 'dreadful', 'specific', 'gather', 'inform', 'intriguing', 'reflect', 'manipulate', 'impose', 'totally', 'surprisingly', '‑', 'conduct', 'consistent', 'discussion', 'entertain', 'milton', 'argue', 'subsequently', 'prominent', 'undoubtedly', 'conclude', 'debate', 'distinguish', 'worthy', 'include', 'drastically', 'disperse', 'recognise', 'allow', 'introduction', 'possibly', 'preserve', 'offer', 'quickly', 'confirm', 'conclusion', 'collect', 'reduce', 'removal', 'consistently', 'distinction', 'previously', 'reduced', 'disappear', 'integrate', 'observe', 'estimate', 'propose', 'potentially', 'minimize', 'explode', 'halt', 'reinforce', 'usage', 'increased', 'invariably', 'involve', 'advocate', 'unable', 'reside', 'described', 'finding', 'primarily', 'improve', 'verify', 'recommendation', 'reassure', 'seldom', 'concerned', 'finally', 'exploration', 'arguably', 'coincide', 'determine', 'improved', '‐', 'rely', 'commonly', 'compelling', 'agree', 'eliminate', 'inability', 'incorporate', 'difficult', 'facilitate', 'subsequent', 'denomination', 'consolidate', 'emergence', 'comprise', 'select', 'explore', 'chiefly', 'depend', 'activate', 'operate', 'prove', 'exploit', 'belong', 'unnoticed', 'largely', 'occur', 'favor', 'rapid', 'exist', 'established', 'ironically', 'define', 'hardly', 'significantly', 'find', 'generally', '1648', 'characterized', 'taxis', 'represent', 'choose', 'especially', 'lastly', 'explanation', 'imply', 'elusive', 'possess', 'dramatically', 'installment', 'provide', 'understand', 'induce', 'locate', 'commonplace', 'extend', 'seek', 'historically', 'outline', 'principally', 'constantly', 'effort', 'deserve', 'reconcile', 'employ', 'systematically', 'reduction', 'intervene', 'originally', 'devote', 'recent', 'achieve', 'indicate', 'apparently', 'continue', 'dozen', 'pointer', 'admit', 'illustrate', 'intersection', 'emerge', 'noteworthy', 'disturb', 'correspond', 'necessarily', 'known', 'perform', 'encourage', 'unexpected', 'generate', 'consequently', 'evolve', 'uncover', 'render', 'discourage', 'contain', 'calculate', 'controversy', 'initially', 'need', 'presence', 'stimulate', 'know', 'implementation', 'emphasize', 'assumption', 'cooperate', 'reject', 'describe', 'fortunately', 'differentiate', 'retain', 'start', 'analogous', 'maintain', 'pursue', 'elevated', 'aside', 'maximize', 'expand', 'abandon', '1824', 'recognize', 'controversial', 'utilize'})
#words = list({'sixteen', 'seventeen', 'fourteen', 'seven', 'eighteen', 'thirty', 'seventy', 'eighty', 'nineteen', 'ninety', 'thirteen'})
giant_clust_df = embeddings.loc[words]

In [19]:
for word in words:
    print(word)
    print(retriever.replaceable_words[word])
    print()

favour
{'favour', 'favor', 'recognise'}

speculation
{'speculation', 'argue'}

contradictory
{'inconsistent', 'contradictory', 'conflicting'}

dismiss
{'conclude', 'accomplish', 'rely', 'originate', 'acknowledge', 'pursue', 'intend', 'overlook', 'dismiss', 'recognise', 'argue'}

consider
{'consideration', 'explain', 'consider', 'understand', 'emphasize', 'discuss', 'explore', 'think', 'describe', 'highlight', 'argue', 'conclude', 'constitute', 'pursue', 'believe', 'employ', 'regard', 'realize', 'propose', 'recognize', 'choose', 'represent', 'utilize'}

hopefully
{'undoubtedly', 'seemingly', 'lately', 'obviously', 'intend', 'supposedly', 'eventually', 'hopefully'}

apply
{'apply', 'employ'}

encouraging
{'surprising', 'encouraging'}

investigate
{'determine', 'find', 'explore', 'examine', 'evaluate', 'discover', 'analyze', 'establish', 'explain', 'describe', 'reveal', 'investigate', 'observe'}

discuss
{'acknowledge', 'involve', 'overlook', 'explain', 'consider', 'emphasize', 'understand', 'discuss', 'specify', 'discussion', 'illustrate', 'explore', 'locate', 'describe', 'disclose', 'highlight', 'argue', 'accompany', 'send', 'proceed', 'conclude', 'debate', 'originate', 'distinguish', 'pursue', 'intend', 'exist', 'owe', 'bring', 'believe', 'employ', 'regard', 'undertake', 'address', 'introduce', 'confront', 'accomplish', 'realize', 'propose', 'rely', 'lay', 'recognize', 'represent', 'comment', 'recognise', 'agree', 'utilize'}

existence
{'presence', 'existence', 'exist'}

appear
{'introduce', 'constitute', 'occur', 'pose', 'discover', 'exist', 'disappear', 'remain', 'explain', 'represent', 'recognize', 'describe', 'believe', 'reveal', 'emerge', 'accompany', 'exhibit', 'appear'}

remarkably
{'remarkably', 'necessarily', 'seemingly', 'apparently', 'remarkable', 'gradually', 'obviously', 'supposedly', 'surprisingly', 'considerably', 'nonetheless'}

seemingly
{'invariably', 'acknowledge', 'obviously', 'hopefully', 'inferno', 'remarkably', 'seemingly', 'commonplace', 'entertain', 'argue', 'surprising', 'undermine', 'undoubtedly', 'proceed', 'globe', 'lately', 'pursue', 'intend', 'owe', 'aside', 'ironically', '‐', 'characterized', 'rely', 'supposedly', 'taxis', 'recognise', 'nonetheless'}

urge
{'urge', 'intend', 'encourage', 'persuade', 'argue'}

decline
{'decline', 'decrease'}

avoid
{'eliminate', 'prevent', 'minimize', 'avoid', 'encourage', 'ignore', 'manage'}

think
{'know', 'think', 'consider', 'believe'}

assess
{'examine', 'evaluate', 'assess'}

resist
{'proceed', 'rely', 'acknowledge', 'pursue', 'owe', 'resist', 'recognise', 'argue', 'undermine'}

highlight
{'acknowledge', 'consider', 'emphasize', 'discuss', 'explore', 'locate', 'illustrate', 'describe', 'highlight', 'argue', 'accompany', 'conclude', 'distinguish', 'pursue', 'intend', 'address', 'introduce', 'represent', 'recognize', 'reveal', 'utilize'}

weaken
{'strengthen', 'weaken'}

disregard
{'acknowledge', 'overlook', 'disregard', 'recognise', 'convince', 'undermine'}

entirely
{'totally', 'completely', 'exclusively', 'entirely'}

manage
{'avoid', 'manage', 'describe'}

strongly
{'clearly', 'strongly'}

accompany
{'assure', 'involve', 'acknowledge', 'imply', 'impose', 'explain', 'possess', 'facilitate', 'justify', 'emphasize', 'comprise', 'appear', 'discuss', 'specify', 'locate', 'illustrate', 'depend', 'obtain', 'describe', 'disclose', 'initiate', 'highlight', 'argue', 'accompany', 'correspond', 'proceed', 'require', 'necessarily', 'conclude', 'constitute', 'originate', 'distinguish', 'coincide', 'pursue', 'exist', 'owe', 'bring', 'intend', 'encourage', 'persuade', 'believe', 'employ', 'undertake', 'introduce', 'rely', 'render', 'consist', 'discourage', 'halt', 'recognize', 'represent', 'recognise', 'reinforce', 'nonetheless', 'utilize'}

discovery
{'discovery', 'discover'}

unexpectedly
{'unexpectedly', 'surprisingly', 'unexpected'}

kill
{'kill', 'destroy'}

proceed
{'depict', 'acknowledge', 'obviously', 'convince', 'inferno', 'discuss', 'seemingly', 'locate', 'commonplace', 'entertain', 'resist', 'exploit', 'initiate', 'argue', 'accompany', 'disturb', 'send', 'undermine', 'undoubtedly', 'proceed', 'conclude', 'globe', 'settle', 'originate', 'vanish', 'pursue', 'intend', 'owe', 'aside', 'persuade', 'undertake', '‐', 'accomplish', 'rely', 'render', 'recognise', 'nonetheless', 'utilize'}

traditionally
{'undoubtedly', 'typically', 'traditionally', 'extensively', 'repeatedly', 'obviously', 'originally', 'historically', 'routinely'}

globe
{'extensively', 'obviously', 'convince', 'seemingly', 'locate', 'commonplace', 'entertain', 'argue', 'undoubtedly', 'proceed', 'globe', 'pursue', 'intend', 'owe', 'aside', 'persuade', 'prosperous', '‐', 'rely', 'recognise'}

clarify
{'clarify', 'verify'}

arise
{'arise', 'emerge'}

lately
{'undoubtedly', 'repeatedly', 'recently', 'seemingly', 'lately', 'obviously', 'intend', 'owe', 'aside', 'recognise', 'hopefully', 'nonetheless'}

frequently
{'constantly', 'occasionally', 'repeatedly', 'typically', 'regularly', 'frequently', 'rarely', 'widely', 'routinely', 'commonly'}

conserve
{'preserve', 'conserve'}

considerably
{'remarkably', 'greatly', 'gradually', 'substantially', 'considerably', 'dramatically', 'significantly'}

advise
{'inform', 'advise', 'recommend'}

recommend
{'suggest', 'recommendation', 'advise', 'recommend'}

repeatedly
{'undoubtedly', 'constantly', 'occasionally', 'repeatedly', 'traditionally', 'extensively', 'rely', 'acknowledge', 'gradually', 'frequently', 'lately', 'intend', 'routinely', 'recognise', 'argue', 'nonetheless'}

dreadful
{'undoubtedly', 'dreadful', 'commonplace', 'owe', 'recognise'}

specific
{'specific', 'particular'}

clearly
{'necessarily', 'clearly', 'apparently', 'obviously', 'strongly'}

gather
{'gather', 'collect'}

differ
{'differ', 'vary', 'depend'}

inform
{'advise', 'inform'}

intriguing
{'intriguing', 'pursue', 'interesting', 'recognise', 'surprising', 'compelling'}

reflect
{'constitute', 'indicate', 'represent', 'reveal', 'reflect'}

manipulate
{'manipulate', 'exploit', 'utilize'}

discreet
{'‐', 'commonplace', 'discreet', 'recognise'}

impose
{'enforce', 'introduce', 'depend', 'impose', 'bring', 'argue', 'accompany'}

overlook
{'acknowledge', 'overlook', 'dismiss', 'convince', 'ignore', 'emphasize', 'discuss', 'locate', 'exploit', 'argue', 'disregard', 'undermine', 'undoubtedly', 'conclude', 'originate', 'vanish', 'pursue', 'intend', 'owe', 'persuade', 'employ', 'educate', 'realize', 'rely', 'recognize', 'recognise', 'appreciate', 'utilize'}

substantially
{'substantially', 'considerably', 'greatly', 'significantly'}

totally
{'totally', 'completely', 'entirely'}

rarely
{'occasionally', 'typically', 'frequently', 'seldom', 'rarely'}

surprisingly
{'remarkably', 'obviously', 'nonetheless', 'surprisingly', 'fortunately', 'surprising', 'unexpectedly'}

‑
{'‑', '‐'}

profoundly
{'undoubtedly', 'profoundly', 'greatly'}

conduct
{'conduct', 'perform'}

consistent
{'inconsistent', 'consistent', 'consistently'}

discussion
{'discuss', 'debate', 'discussion'}

worried
{'undoubtedly', 'worried', 'intend', 'owe', 'recognise'}

discover
{'explain', 'investigate', 'understand', 'appear', 'explore', 'locate', 'discover', 'describe', 'discovery', 'demonstrate', 'determine', 'introduce', 'uncover', 'find', 'realize', 'propose', 'establish', 'recognize', 'develop', 'reveal'}

remarkable
{'noteworthy', 'remarkably', 'remarkable', 'notable'}

entertain
{'acknowledge', 'obviously', 'denomination', 'convince', 'inferno', 'seemingly', 'commonplace', 'entertain', 'argue', 'undermine', 'undoubtedly', 'proceed', 'globe', 'vanish', 'pursue', 'intend', 'owe', 'ironically', 'prosperous', '1824', '‐', 'suggested', 'rely', 'recognise', 'nonetheless'}

milton
{'‐', 'vanish', 'milton', 'denomination', 'inferno'}

use
{'use', 'utilize', 'usage'}

gives
{'commonplace', 'denomination', 'recognise', 'gives'}

argue
{'depict', 'speculation', 'dismiss', 'consider', 'consolidate', 'justify', 'discuss', 'seemingly', 'specify', 'urge', 'explore', 'resist', 'exploit', 'highlight', 'accompany', 'undermine', 'proceed', 'globe', 'exist', 'repeatedly', 'taxis', 'imply', 'obviously', 'impose', 'overlook', 'understand', 'locate', 'entertain', 'argue', 'undoubtedly', 'conclude', 'distinguish', 'bring', 'reconcile', 'employ', 'introduce', 'recognise', 'devote', 'notion', 'extensively', 'dozen', 'come', 'admit', 'illustrate', 'constitute', 'settle', 'originate', 'vanish', 'intend', 'owe', 'believe', 'educate', 'confront', 'accomplish', 'propose', 'render', 'discourage', 'supposedly', 'lay', 'reinforce', 'claim', 'assure', 'acknowledge', 'advocate', 'explain', 'convince', 'emphasize', 'reject', 'describe', 'initiate', 'satisfy', 'cloak', 'send', 'lend', 'pursue', 'aside', 'impossible', 'persuade', 'undertake', '‐', 'realize', 'rely', 'recognize', 'nonetheless', 'utilize'}

virtually
{'practically', 'largely', 'essentially', 'virtually'}

subsequently
{'eventually', 'subsequent', 'subsequently', 'consequently', 'ultimately'}

prominent
{'notable', 'prominent'}

remove
{'eliminate', 'removal', 'remove'}

undoubtedly
{'interceptor', 'posse', 'extensively', 'invariably', 'acknowledge', 'obviously', 'elusive', 'overlook', 'denomination', 'hopefully', 'consolidate', 'convince', 'inferno', 'profoundly', 'pedro', 'multitude', 'seemingly', 'worried', 'locate', 'commonplace', 'entertain', 'evidently', 'exploit', 'argue', 'surprising', 'disturb', 'undermine', 'undoubtedly', 'proceed', 'necessarily', 'traditionally', 'theoretically', 'capable', 'globe', 'lush', 'analogous', 'originate', 'vanish', 'pursue', 'lately', 'intend', 'owe', 'aside', 'ironically', 'impossible', 'persuade', 'prosperous', 'reconcile', 'undertake', 'repeatedly', 'dreadful', 'confront', '‐', 'realize', 'characterized', 'rely', 'supposedly', 'taxis', 'recognize', 'recognise', 'nonetheless', 'lastly', 'utilize'}

conclude
{'compose', 'acknowledge', 'imply', 'involve', 'overlook', 'explain', 'dismiss', 'consider', 'justify', 'emphasize', 'discuss', 'specify', 'explore', 'illustrate', 'verify', 'locate', 'assume', 'obtain', 'describe', 'disclose', 'initiate', 'highlight', 'conclusion', 'argue', 'accompany', 'proceed', 'conclude', 'constitute', 'settle', 'originate', 'distinguish', 'pursue', 'intend', 'exist', 'persuade', 'believe', 'begin', 'employ', 'undertake', 'determine', 'accomplish', 'realize', 'propose', 'rely', 'consist', 'halt', 'establish', 'recognize', 'represent', 'recognise', 'nonetheless', 'agree', 'utilize'}

debate
{'debate', 'discussion', 'dispute', 'controversy', 'discuss'}

distinguish
{'acknowledge', 'understand', 'emphasize', 'discuss', 'specify', 'locate', 'highlight', 'argue', 'accompany', 'differentiate', 'distinction', 'conclude', 'originate', 'distinguish', 'pursue', 'exist', 'persuade', 'rely', 'recognize', 'recognise', 'utilize'}

briefly
{'intend', 'briefly', 'extensively'}

bring
{'acknowledge', 'impose', 'allow', 'come', 'discuss', 'admit', 'locate', 'exploit', 'initiate', 'argue', 'accompany', 'send', 'originate', 'pursue', 'intend', 'owe', 'bring', 'persuade', 'believe', 'introduce', 'realize', 'rely', 'render', 'recognize', 'recognise', 'utilize'}

formidable
{'formidable', 'vanish'}

compute
{'compute', 'calculate'}

worthy
{'worthy', 'recognise'}

include
{'involve', 'consist', 'incorporate', 'include', 'contain', 'provide'}

drastically
{'drastically', 'greatly', 'dramatically'}

address
{'address', 'pose', 'discuss', 'highlight'}

introduce
{'acknowledge', 'obviously', 'incorporate', 'impose', 'explain', 'introduction', 'emphasize', 'understand', 'appear', 'discuss', 'offer', 'admit', 'explore', 'locate', 'illustrate', 'discover', 'describe', 'initiate', 'highlight', 'emerge', 'argue', 'exploit', 'accompany', 'constitute', 'originate', 'pursue', 'intend', 'exist', 'owe', 'bring', 'encourage', 'employ', 'implement', 'introduce', 'realize', 'propose', 'rely', 'establish', 'recognize', 'represent', 'recognise', 'reveal', 'utilize'}

disperse
{'disperse', 'distribute'}

slow
{'slow', 'rapid'}

enable
{'enable', 'allow', 'facilitate', 'encourage', 'provide'}

build
{'establish', 'build', 'create', 'develop'}

display
{'exhibit', 'demonstrate', 'display'}

gradually
{'constantly', 'remarkably', 'rapidly', 'repeatedly', 'finally', 'steadily', 'quickly', 'gradually', 'eventually', 'slowly', 'considerably'}

recognise
{'favour', 'depict', 'denomination', 'dismiss', 'consolidate', 'uphold', 'discuss', 'seemingly', 'specify', 'resist', 'exploit', 'disregard', 'accompany', 'undermine', 'unnoticed', 'proceed', 'globe', 'lush', 'lately', 'exist', 'ironically', 'repeatedly', 'dreadful', '1648', 'characterized', 'taxis', 'intriguing', 'discreet', 'obviously', 'elusive', 'overlook', 'possess', 'understand', 'worried', 'locate', 'commonplace', 'entertain', 'gives', 'argue', 'undoubtedly', 'conclude', 'distinguish', 'bring', 'worthy', 'confuse', 'reconcile', 'employ', 'introduce', 'recognise', 'appreciate', 'devote', 'notion', 'extensively', 'dozen', 'pointer', 'inferno', 'organise', 'admit', 'disturb', 'constitute', 'settle', 'originate', 'vanish', 'intend', 'owe', 'believe', 'educate', 'confront', 'accomplish', 'render', 'interested', 'explode', 'discourage', 'supposedly', 'reinforce', 'interceptor', 'posse', 'invariably', 'assure', 'acknowledge', 'described', 'convince', 'emphasize', 'pedro', 'multitude', 'surprising', 'satisfy', 'cloak', 'send', 'analogous', 'coincide', 'pursue', 'aside', 'impossible', 'persuade', 'prosperous', 'shepherd', '1824', 'undertake', '‐', 'realize', 'rely', 'recognize', 'nonetheless', 'utilize'}

appreciate
{'realize', 'acknowledge', 'overlook', 'recognize', 'enjoy', 'recognise', 'appreciate', 'understand'}

essentially
{'largely', 'essentially', 'virtually'}

extensively
{'extensively', 'obviously', 'multitude', 'argue', 'undoubtedly', 'constantly', 'traditionally', 'globe', 'pursue', 'briefly', 'intend', 'owe', 'routinely', 'employ', 'undertake', 'repeatedly', 'accomplish', 'rely', 'recognise', 'nonetheless', 'lastly', 'utilize'}

allow
{'require', 'offer', 'enable', 'involve', 'permit', 'exist', 'bring', 'facilitate', 'encourage', 'allow', 'provide', 'employ'}

mainly
{'largely', 'chiefly', 'mainly', 'primarily', 'principally'}

acquire
{'obtain', 'acquire'}

unusual
{'unexpected', 'unusual'}

inferno
{'depict', 'obviously', 'denomination', 'consolidate', 'convince', 'inferno', 'seemingly', 'commonplace', 'milton', 'entertain', 'undermine', 'undoubtedly', 'proceed', 'vanish', 'pursue', 'intend', 'owe', 'ironically', '‐', 'recognise'}

introduction
{'introduction', 'introduce'}

possibly
{'potentially', 'probably', 'possibly', 'presumably'}

analyze
{'examine', 'evaluate', 'investigate', 'analyze'}

preserve
{'retain', 'maintain', 'preserve', 'conserve'}

offer
{'introduce', 'offer', 'propose', 'allow', 'represent', 'provide'}

quickly
{'rapidly', 'gradually', 'slowly', 'quickly'}

confirm
{'determine', 'verify', 'indicate', 'confirm', 'establish', 'prove', 'reveal'}

await
{'deserve', 'intend', 'pursue', 'await'}

conclusion
{'conclude', 'conclusion'}

inconsistent
{'inconsistent', 'consistent', 'contradictory', 'conflicting'}

collect
{'gather', 'collect', 'collection', 'obtain'}

reduce
{'minimize', 'decrease', 'increase', 'reduce', 'reduction'}

removal
{'removal', 'remove'}

consistently
{'routinely', 'consistent', 'consistently'}

distinction
{'distinction', 'distinguish'}

previously
{'previously', 'originally', 'recently', 'previous'}

reduced
{'diminished', 'reduced', 'increased'}

collection
{'collect', 'collection'}

require
{'require', 'involve', 'imply', 'need', 'seek', 'allow', 'obtain', 'accompany'}

evaluate
{'examine', 'evaluate', 'assess', 'analyze', 'investigate'}

settle
{'proceed', 'conclude', 'locate', 'settle', 'rely', 'originate', 'vanish', 'pursue', 'render', 'intend', 'persuade', 'recognise', 'argue'}

previous
{'previously', 'previous'}

intend
{'dismiss', 'hopefully', 'consolidate', 'justify', 'discuss', 'seemingly', 'specify', 'urge', 'explore', 'exploit', 'highlight', 'accompany', 'undermine', 'proceed', 'capable', 'globe', 'lately', 'exist', 'repeatedly', '1648', 'characterized', 'taxis', 'imply', 'obviously', 'overlook', 'worried', 'locate', 'commonplace', 'entertain', 'seek', 'argue', 'undoubtedly', 'conclude', 'briefly', 'bring', 'underway', 'reconcile', 'employ', 'introduce', 'intervene', 'recognise', 'devote', 'notion', 'extensively', 'dozen', 'inferno', 'organise', 'admit', 'evidently', 'await', 'disturb', 'necessarily', 'constitute', 'settle', 'originate', 'vanish', 'intend', 'owe', 'believe', 'confront', 'accomplish', 'propose', 'render', 'interested', 'discourage', 'supposedly', 'lay', 'interceptor', 'assure', 'acknowledge', 'advocate', 'convince', 'emphasize', 'cooperate', 'initiate', 'surprising', 'satisfy', 'cloak', 'send', 'coincide', 'pursue', 'aside', 'impossible', 'persuade', 'prosperous', 'undertake', '‐', 'realize', 'rely', 'consist', 'recognize', 'nonetheless', 'utilize'}

able
{'capable', 'able', 'unable'}

owe
{'notion', 'posse', 'extensively', 'acknowledge', 'obviously', 'overlook', 'possess', 'dozen', 'convince', 'inferno', 'uphold', 'discuss', 'admit', 'specify', 'worried', 'seemingly', 'commonplace', 'locate', 'entertain', 'cooperate', 'resist', 'exploit', 'argue', 'surprising', 'accompany', 'disturb', 'undermine', 'satisfy', 'send', 'undoubtedly', 'proceed', 'constitute', 'globe', 'analogous', 'originate', 'vanish', 'lend', 'pursue', 'exist', 'owe', 'aside', 'bring', 'lately', 'persuade', 'believe', 'intend', 'prosperous', 'reconcile', 'undertake', 'introduce', '‐', 'dreadful', 'confront', 'accomplish', 'realize', 'characterized', 'rely', 'supposedly', 'taxis', 'recognize', 'recognise', 'nonetheless', 'utilize', 'devote'}

accumulate
{'accumulate', 'generate', 'obtain'}

disappear
{'disappearance', 'eliminate', 'disappear', 'appear'}

believe
{'claim', 'acknowledge', 'explain', 'possess', 'consider', 'know', 'understand', 'emphasize', 'appear', 'discuss', 'admit', 'locate', 'think', 'describe', 'belong', 'argue', 'accompany', 'conclude', 'constitute', 'originate', 'pursue', 'intend', 'exist', 'owe', 'bring', 'persuade', 'believe', 'employ', 'realize', 'propose', 'rely', 'consist', 'interested', 'recognize', 'recognise', 'utilize'}

varied
{'varied', 'vary'}

disappearance
{'disappearance', 'disappear'}

reach
{'obtain', 'achieve', 'reach'}

increase
{'increased', 'decrease', 'rise', 'increase', 'reduce'}

integrate
{'integrate', 'incorporate', 'utilize'}

observe
{'examine', 'investigate', 'observe'}

estimate
{'estimation', 'calculate', 'estimate'}

occasionally
{'rarely', 'repeatedly', 'frequently', 'occasionally'}

actually
{'actually', 'finally'}

suggested
{'suggested', 'entertain'}

accordingly
{'consequently', 'accordingly'}

propose
{'imply', 'suggest', 'explain', 'consider', 'justify', 'discuss', 'offer', 'explore', 'discover', 'describe', 'initiate', 'argue', 'outline', 'conclude', 'pursue', 'intend', 'believe', 'implement', 'introduce', 'realize', 'propose'}

potentially
{'potentially', 'possibly'}

minimize
{'alleviate', 'minimize', 'avoid', 'maximize', 'reduce'}

decrease
{'decline', 'decrease', 'increase', 'reduce', 'reduction'}

interested
{'obviously', 'interested', 'intend', 'persuade', 'believe', 'concerned', 'recognise'}

solely
{'exclusively', 'primarily', 'solely'}

explode
{'commonplace', '‐', 'recognise', 'explode'}

supposedly
{'undoubtedly', 'remarkably', 'necessarily', 'seemingly', 'theoretically', 'apparently', 'obviously', 'pursue', 'intend', 'owe', 'supposedly', 'ironically', 'impossible', 'nonetheless', 'recognise', 'argue', 'hopefully', 'satisfy'}

establish
{'achieve', 'provide', 'investigate', 'specify', 'explore', 'locate', 'verify', 'discover', 'confirm', 'obtain', 'describe', 'initiate', 'demonstrate', 'conclude', 'constitute', 'create', 'maintain', 'established', 'define', 'generate', 'employ', 'implement', 'determine', 'introduce', 'build', 'identify', 'strengthen', 'establish', 'recognize', 'develop'}

lay

In [44]:
giant_clust_df

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
favour,-0.109791,1.054143,0.855609,-0.416565,0.045719,0.347847,0.733342,-1.137669,-0.235586,-0.618637,...,0.369878,-0.169957,-0.217157,0.337167,0.407337,-0.457875,-1.206020,-0.579232,-0.458474,-0.712602
speculation,0.659854,0.186321,0.727573,-0.446819,0.380351,-0.210993,-0.059252,-0.327786,-0.002517,-0.448875,...,0.255106,-0.064426,-0.146203,0.400718,0.182539,-0.836347,-0.197009,-0.460947,0.002866,-0.223719
contradictory,-0.049996,0.539641,0.844817,-0.358280,-0.394133,-0.328650,0.377281,0.156704,-0.400049,0.000043,...,0.176304,0.023139,-0.726776,0.189081,0.058119,-0.557637,-0.713782,-0.347550,-0.150325,-0.515758
dismiss,0.295157,0.414573,0.320630,-0.343978,-0.228544,-0.437348,0.296916,-1.138054,0.373716,-0.680208,...,0.249827,-0.166024,-0.322037,0.093139,0.267391,0.337375,-0.499645,-0.156503,-0.108286,0.486218
consider,-0.694869,1.053351,0.448832,-0.829067,0.511981,0.077333,0.457517,-0.999839,0.131944,-0.655912,...,-0.303912,-0.461297,0.072514,0.340565,0.152009,-0.079753,-0.226414,-0.565276,-0.419219,-0.128325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
typically,-0.173377,1.079988,0.450534,-0.625592,-0.423852,-0.348596,0.708687,-0.044938,-0.068207,-0.764698,...,-0.305740,-0.278270,-0.250443,0.360198,0.004940,-0.774514,-0.547480,-0.474829,-0.523229,0.081346
understanding,-0.958623,1.349883,0.355833,-0.542287,1.058054,0.358362,0.255246,-0.366785,0.042249,-0.520878,...,-0.030133,-0.082717,0.183507,-0.046963,-0.191727,-0.157411,-0.020714,-0.704141,-0.299981,0.050186
recognize,-0.174776,1.378860,0.345857,-0.737986,0.485873,-0.391939,0.346718,-0.761412,0.425492,-0.724033,...,-0.098417,-0.207951,0.099399,0.366424,0.077238,-0.196383,0.108798,-0.686356,-0.552575,0.130069
controversial,-0.263400,0.916472,0.616372,-0.344162,-0.349287,-0.511096,0.109149,-0.428929,-0.697751,0.195309,...,-0.409249,-0.202927,-0.088755,-0.103370,0.198205,-0.792695,0.120934,-0.402693,-0.495720,-0.269850
predominantly,-0.102518,0.871293,0.448298,-0.774335,-0.389240,0.078859,0.744882,-0.192235,0.313622,-0.221692,...,-0.089264,-0.251172,-0.010824,0.786697,0.306184,-0.509173,-0.516631,-0.481937,-0.645392,-0.192879

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances
import numpy as np


dist_from_center_df = pd.DataFrame(cosine_distances(embeddings, np.array(embeddings.mean(axis=0)).reshape(1, -1)))
dist_from_center_df.index = embeddings.index

In [38]:
dist_from_center_df.describe()

                  0
count  11342.000000
mean       0.391788
std        0.108841
min        0.171113
25%        0.306821
50%        0.372907
75%        0.460353
max        1.169017

# Make a research

In [ ]:
n_doc = 5 # number of documents to retrieve
query = {list(queries.items())[0][0]:list(queries.items())[0][1]}
print(query)

{'PLAIN-2': 'Do Cholesterol Statin Drugs Cause Breast Cancer?'}

In [ ]:
results = retriever.search(cleaned_corpus, query, n_doc, 'cos_sim') # example of a search
results

tests in progress: 100%|██████████| 1/1 [00:00<00:00, 46.02it/s]

{'PLAIN-2': {'MED-10': 20.93295349819547,
  'MED-14': 20.655786888914797,
  'MED-2429': 17.76914486418028,
  'MED-1193': 17.639927340902968,
  'MED-2431': 16.98124248214051}}

In [ ]:
for quer_id in list(results.keys()):
    print(f'Query: {queries[quer_id]}')
    for doc_id in list(results[quer_id].keys()):
        print('\n')
        print(f'\tDocument: {corpus[doc_id]}')
        print(f'\tScore: {results[quer_id][doc_id]}')
    
    print('\n')

Query: Do Cholesterol Statin Drugs Cause Breast Cancer?


	Document: {'text': 'Recent studies have suggested that statins, an established drug group in the prevention of cardiovascular mortality, could delay or prevent breast cancer recurrence but the effect on disease-specific mortality remains unclear. We evaluated risk of breast cancer death among statin users in a population-based cohort of breast cancer patients. The study cohort included all newly diagnosed breast cancer patients in Finland during 1995–2003 (31,236 cases), identified from the Finnish Cancer Registry. Information on statin use before and after the diagnosis was obtained from a national prescription database. We used the Cox proportional hazards regression method to estimate mortality among statin users with statin use as time-dependent variable. A total of 4,151 participants had used statins. During the median follow-up of 3.25 years after the diagnosis (range 0.08–9.0 years) 6,011 participants died, of which 3,619 (60.2%) was due to breast cancer. After adjustment for age, tumor characteristics, and treatment selection, both post-diagnostic and pre-diagnostic statin use were associated with lowered risk of breast cancer death (HR 0.46, 95% CI 0.38–0.55 and HR 0.54, 95% CI 0.44–0.67, respectively). The risk decrease by post-diagnostic statin use was likely affected by healthy adherer bias; that is, the greater likelihood of dying cancer patients to discontinue statin use as the association was not clearly dose-dependent and observed already at low-dose/short-term use. The dose- and time-dependence of the survival benefit among pre-diagnostic statin users suggests a possible causal effect that should be evaluated further in a clinical trial testing statins’ effect on survival in breast cancer patients.', 'title': 'Statin Use and Breast Cancer Survival: A Nationwide Cohort Study from Finland'}
	Score: 20.93295349819547


	Document: {'text': 'BACKGROUND: Preclinical studies have shown that statins, particularly simvastatin, can prevent growth in breast cancer cell lines and animal models. We investigated whether statins used after breast cancer diagnosis reduced the risk of breast cancer-specific, or all-cause, mortality in a large cohort of breast cancer patients. METHODS: A cohort of 17,880 breast cancer patients, newly diagnosed between 1998 and 2009, was identified from English cancer registries (from the National Cancer Data Repository). This cohort was linked to the UK Clinical Practice Research Datalink, providing prescription records, and to the Office of National Statistics mortality data (up to 2013), identifying 3694 deaths, including 1469 deaths attributable to breast cancer. Unadjusted and adjusted hazard ratios (HRs) for breast cancer-specific, and all-cause, mortality in statin users after breast cancer diagnosis were calculated using time-dependent Cox regression models. Sensitivity analyses were conducted using multiple imputation methods, propensity score methods and a case-control approach. RESULTS: There was some evidence that statin use after a diagnosis of breast cancer had reduced mortality due to breast cancer and all causes (fully adjusted HR = 0.84 [95% confidence interval = 0.68-1.04] and 0.84 [0.72-0.97], respectively). These associations were more marked for simvastatin 0.79 (0.63-1.00) and 0.81 (0.70-0.95), respectively. CONCLUSIONS: In this large population-based breast cancer cohort, there was some evidence of reduced mortality in statin users after breast cancer diagnosis. However, these associations were weak in magnitude and were attenuated in some sensitivity analyses.', 'title': 'Statin use after diagnosis of breast cancer and survival: a population-based cohort study.'}
	Score: 20.655786888914797


	Document: {'text': "Emerging evidence suggests that statins' may decrease the risk of cancers. However, available evidence on breast cancer is conflicting. We, therefore, examined the association between statin use and risk of breast cancer by conducting a detailed meta-analysis of all observational studies published regarding this subject. PubMed database and bibliographies of retrieved articles were searched for epidemiological studies published up to January 2012, investigating the relationship between statin use and breast cancer. Before meta-analysis, the studies were evaluated for publication bias and heterogeneity. Combined relative risk (RR) and 95 % confidence interval (CI) were calculated using a random-effects model (DerSimonian and Laird method). Subgroup analyses, sensitivity analysis, and cumulative meta-analysis were also performed. A total of 24 (13 cohort and 11 case-control) studies involving more than 2.4 million participants, including 76,759 breast cancer cases contributed to this analysis. We found no evidence of publication bias and evidence of heterogeneity among the studies. Statin use and long-term statin use did not significantly affect breast cancer risk (RR = 0.99, 95 % CI = 0.94, 1.04 and RR = 1.03, 95 % CI = 0.96, 1.11, respectively). When the analysis was stratified into subgroups, there was no evidence that study design substantially influenced the effect estimate. Sensitivity analysis confirmed the stability of our results. Cumulative meta-analysis showed a change in trend of reporting risk of breast cancer from positive to negative in statin users between 1993 and 2011. Our meta-analysis findings do not support the hypothesis that statins' have a protective effect against breast cancer. More randomized clinical trials and observational studies are needed to confirm this association with underlying biological mechanisms in the future.", 'title': 'Statin use and risk of breast cancer: a meta-analysis of observational studies.'}
	Score: 17.76914486418028


	Document: {'text': 'Summary Background Statins reduce LDL cholesterol and prevent vascular events, but their net effects in people at low risk of vascular events remain uncertain. Methods This meta-analysis included individual participant data from 22 trials of statin versus control (n=134\u2008537; mean LDL cholesterol difference 1·08 mmol/L; median follow-up 4·8 years) and five trials of more versus less statin (n=39\u2008612; difference 0·51 mmol/L; 5·1 years). Major vascular events were major coronary events (ie, non-fatal myocardial infarction or coronary death), strokes, or coronary revascularisations. Participants were separated into five categories of baseline 5-year major vascular event risk on control therapy (no statin or low-intensity statin) (<5%, ≥5% to <10%, ≥10% to <20%, ≥20% to <30%, ≥30%); in each, the rate ratio (RR) per 1·0 mmol/L LDL cholesterol reduction was estimated. Findings Reduction of LDL cholesterol with a statin reduced the risk of major vascular events (RR 0·79, 95% CI 0·77–0·81, per 1·0 mmol/L reduction), largely irrespective of age, sex, baseline LDL cholesterol or previous vascular disease, and of vascular and all-cause mortality. The proportional reduction in major vascular events was at least as big in the two lowest risk categories as in the higher risk categories (RR per 1·0 mmol/L reduction from lowest to highest risk: 0·62 [99% CI 0·47–0·81], 0·69 [99% CI 0·60–0·79], 0·79 [99% CI 0·74–0·85], 0·81 [99% CI 0·77–0·86], and 0·79 [99% CI 0·74–0·84]; trend p=0·04), which reflected significant reductions in these two lowest risk categories in major coronary events (RR 0·57, 99% CI 0·36–0·89, p=0·0012, and 0·61, 99% CI 0·50–0·74, p<0·0001) and in coronary revascularisations (RR 0·52, 99% CI 0·35–0·75, and 0·63, 99% CI 0·51–0·79; both p<0·0001). For stroke, the reduction in risk in participants with 5-year risk of major vascular events lower than 10% (RR per 1·0 mmol/L LDL cholesterol reduction 0·76, 99% CI 0·61–0·95, p=0·0012) was also similar to that seen in higher risk categories (trend p=0·3). In participants without a history of vascular disease, statins reduced the risks of vascular (RR per 1·0 mmol/L LDL cholesterol reduction 0·85, 95% CI 0·77–0·95) and all-cause mortality (RR 0·91, 95% CI 0·85–0·97), and the proportional reductions were similar by baseline risk. There was no evidence that reduction of LDL cholesterol with a statin increased cancer incidence (RR per 1·0 mmol/L LDL cholesterol reduction 1·00, 95% CI 0·96–1·04), cancer mortality (RR 0·99, 95% CI 0·93–1·06), or other non-vascular mortality. Interpretation In individuals with 5-year risk of major vascular events lower than 10%, each 1 mmol/L reduction in LDL cholesterol produced an absolute reduction in major vascular events of about 11 per 1000 over 5 years. This benefit greatly exceeds any known hazards of statin therapy. Under present guidelines, such individuals would not typically be regarded as suitable for LDL-lowering statin therapy. The present report suggests, therefore, that these guidelines might need to be reconsidered. Funding British Heart Foundation; UK Medical Research Council; Cancer Research UK; European Community Biomed Programme; Australian National Health and Medical Research Council; National Heart Foundation, Australia.', 'title': 'The effects of lowering LDL cholesterol with statin therapy in people at low risk of vascular disease: meta-analysis of individual data from 27 randomised trials'}
	Score: 17.639927340902968


	Document: {'text': 'Background Mechanistic studies largely support the chemopreventive potential of statins. However, results of epidemiologic studies investigating statin use and breast cancer risk have been inconsistent and lacked the ability to evaluate long-term statin use. Materials and Methods We utilized data from a population-based case-control study of breast cancer conducted in the Seattle-Puget Sound region to investigate the relationship between long-term statin use and breast cancer risk. 916 invasive ductal carcinoma (IDC) and 1,068 invasive lobular carcinoma (ILC) cases 55-74 years of age diagnosed between 2000 and 2008 were compared to 902 control women. All participants were interviewed in-person and data on hypercholesterolemia and all episodes of lipid lowering medication use were collected through a structured questionnaire. We assessed the relationship between statin use and IDC and ILC risk using polytomous logistic regression. Results Current users of statins for 10 years or longer had a 1.83-fold increased risk of IDC [95% confidence interval (CI): 1.14-2.93] and a 1.97-fold increased risk of ILC (95% CI: 1.25-3.12) compared to never users of statins. Among women diagnosed with hypercholesterolemia, current users of statins for 10 years or longer had more than double the risk of both IDC [odds ratio (OR): 2.04, 95% CI: 1.17-3.57] and ILC (OR: 2.43, 95% CI: 1.40-4.21) compared to never users. Conclusion In this contemporary population-based case-control study long-term use of statins was associated with increased risks of both IDC and ILC. Impact Additional studies with similarly high frequencies of statin use for various durations are needed to confirm this novel finding.', 'title': 'Long-term statin use and risk of ductal and lobular breast cancer among women 55-74 years of age'}
	Score: 16.98124248214051

In [25]:
scores[0]['NDCG@10']

0.31997

# Finetuning

In [28]:
import numpy as np

alphas = np.linspace(0.5, 1, 10)
threshs = np.linspace(0.5, 1, 10)
best_score = 0
b_alpha = 0
b_thresh = 0

path_res = f'results/results_{dataset}_BERT_finetuning.csv'

for a in alphas:
    for t in threshs:
        scores = {}
        retriever = retriever_model.UCFIRe(embeddings, None,n_neighbors = best_n_neighbors, alpha=a, thresh = t, metric = metric, k1 = k1, b = b, thresh_prob=thresh_prob)

        retriever.fit(cleaned_corpus, is_clean=True, knn_method=knn_method)
        retriever_okapi = EvaluateRetrieval(retriever, score_function="cos_sim") # or "dot" if you wish dot-product
        results_okapi = retriever_okapi.retrieve(retriever.tokenized_corpus, queries)
        # Evaluate the model (implement your own evaluation logic, e.g., compute mean reciprocal rank)
        scores = retriever_okapi.evaluate(qrels, results_okapi, retriever_okapi.k_values)  # Replace this with your evaluation metric

        if save_scores != '':
            with open(save_scores, 'w') as f:
                f.write(str(scores))
        
        if scores[0]['NDCG@10'] > best_score:
            best_score = scores[0]['NDCG@10']
            b_alpha = a
            b_thresh = t

        print(f'Best score so far: {best_score}')
        print(f'Best alpha: {b_alpha}')
        print(f'Best thresh: {b_thresh}')

        dico_scores = {}

        for i in scores:
            dico_scores.update(i)

        pd.DataFrame([a, best_n_neighbors, t, False]+list(dico_scores.values()), index=['alpha', 'n_neighbors', 'thresholds', 'unseen_words_replaced']+list(dico_scores.keys())).T.to_csv(path_res, index=False, mode='a', header=not os.path.exists(path_res))

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 415.24it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9231.14it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 427.99it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 375.79it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:24<00:00, 134.86it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 11173.84it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10252/10252 [00:00<00:00, 1571293.01it/s]
100%|██████████| 3633/3633 [00:14<00:00, 250.71it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 96.20it/s]

Best score so far: 0.31992
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 423.90it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9323.87it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 431.01it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 402.45it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:35<00:00, 118.91it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 11979.51it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10623/10623 [00:00<00:00, 1711392.03it/s]
100%|██████████| 3633/3633 [00:13<00:00, 271.69it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 97.62it/s]

Best score so far: 0.32
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 420.77it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9995.46it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 421.42it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 402.36it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:32<00:00, 123.15it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 10165.15it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10801/10801 [00:00<00:00, 1538343.49it/s]
100%|██████████| 3633/3633 [00:17<00:00, 202.70it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 85.68it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 376.63it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 6250.85it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 355.39it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 361.86it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:32<00:00, 122.42it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 10050.45it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10887/10887 [00:00<00:00, 1211583.95it/s]
100%|██████████| 3633/3633 [00:16<00:00, 213.90it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 81.24it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 364.19it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7568.96it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 347.95it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 358.69it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:34<00:00, 120.33it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 7241.14it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10930/10930 [00:00<00:00, 1029803.06it/s]
100%|██████████| 3633/3633 [00:23<00:00, 151.65it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 64.86it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:13<00:00, 260.30it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:02<00:00, 5586.75it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:13<00:00, 260.52it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:15<00:00, 237.43it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:42<00:00, 110.45it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 10308.39it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11028/11028 [00:00<00:00, 1377409.38it/s]
100%|██████████| 3633/3633 [00:17<00:00, 212.96it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 80.63it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 373.51it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7574.86it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 375.00it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 353.83it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:53<00:00, 99.58it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 7180.57it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11182/11182 [00:00<00:00, 1311944.60it/s]
100%|██████████| 3633/3633 [00:22<00:00, 162.52it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 70.76it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 251.69it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 5893.42it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 259.11it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:14<00:00, 243.30it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:08<00:00, 88.43it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 7067.50it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11286/11286 [00:00<00:00, 979877.76it/s]
100%|██████████| 3633/3633 [00:22<00:00, 163.04it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 70.11it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 251.48it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 5672.34it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 249.88it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:15<00:00, 234.10it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:07<00:00, 89.14it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 8754.95it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11338/11338 [00:00<00:00, 1190959.65it/s]
100%|██████████| 3633/3633 [00:23<00:00, 153.78it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 69.19it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:11<00:00, 315.53it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8154.21it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 389.62it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 363.15it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:33<00:00, 120.98it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 10588.35it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<00:00, 1539866.85it/s]
100%|██████████| 3633/3633 [00:17<00:00, 206.48it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 75.48it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 381.86it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8268.95it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 394.88it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 393.56it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:23<00:00, 136.39it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 8092.87it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 9506/9506 [00:00<00:00, 506562.83it/s]
100%|██████████| 3633/3633 [00:17<00:00, 206.18it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 76.71it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 331.41it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 6175.03it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:12<00:00, 300.75it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 345.96it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:29<00:00, 126.13it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 9217.80it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10539/10539 [00:00<00:00, 1294969.09it/s]
100%|██████████| 3633/3633 [00:17<00:00, 212.27it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 82.53it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 375.79it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7922.33it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 368.18it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 349.41it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:32<00:00, 122.70it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 9286.28it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10775/10775 [00:00<00:00, 993375.66it/s]
100%|██████████| 3633/3633 [00:17<00:00, 212.43it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 86.86it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 360.32it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7318.31it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 369.64it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 360.96it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:31<00:00, 123.51it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 11423.57it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10889/10889 [00:00<00:00, 1051109.90it/s]
100%|██████████| 3633/3633 [00:16<00:00, 224.99it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 82.14it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 348.24it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7859.11it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 363.53it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 341.67it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:00<00:00, 94.47it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 6985.81it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10966/10966 [00:01<00:00, 9131.64it/s]
100%|██████████| 3633/3633 [00:20<00:00, 173.01it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 91.95it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 389.83it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 6725.92it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 362.57it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 350.20it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:29<00:00, 126.07it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 9956.24it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11091/11091 [00:00<00:00, 1248832.90it/s]
100%|██████████| 3633/3633 [00:17<00:00, 211.12it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 88.43it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 398.43it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7850.71it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 382.03it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 370.47it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:21<00:00, 139.13it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 12698.04it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11220/11220 [00:00<00:00, 2077249.65it/s]
100%|██████████| 3633/3633 [00:13<00:00, 261.29it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 96.64it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 385.39it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8624.37it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 390.82it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 376.14it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:21<00:00, 139.73it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 11298.63it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11309/11309 [00:00<00:00, 981448.04it/s]
100%|██████████| 3633/3633 [00:14<00:00, 250.24it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 93.39it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 367.62it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7462.42it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 388.53it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 388.38it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:22<00:00, 138.18it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 13709.06it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11338/11338 [00:00<00:00, 1470697.97it/s]
100%|██████████| 3633/3633 [00:14<00:00, 256.19it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 91.83it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 390.71it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8622.44it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 391.50it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 386.82it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:39<00:00, 114.27it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 9169.34it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<00:00, 942708.36it/s]
100%|██████████| 3633/3633 [00:24<00:00, 150.84it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 66.18it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 245.11it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:02<00:00, 4945.04it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:15<00:00, 240.53it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:15<00:00, 238.85it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:09<00:00, 87.60it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:03<00:00, 3767.67it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 7485/7485 [00:00<00:00, 478448.66it/s]
100%|██████████| 3633/3633 [00:26<00:00, 136.43it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 67.68it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 253.32it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 6116.09it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 252.95it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:15<00:00, 234.74it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:11<00:00, 86.37it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:02<00:00, 5289.27it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10078/10078 [00:00<00:00, 803906.27it/s]
100%|██████████| 3633/3633 [00:27<00:00, 133.23it/s]
tests in progress: 100%|██████████| 323/323 [00:05<00:00, 59.06it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:17<00:00, 209.87it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:02<00:00, 5310.63it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:16<00:00, 214.55it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:17<00:00, 202.18it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:26<00:00, 77.52it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:04<00:00, 2775.33it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10727/10727 [00:00<00:00, 1087085.60it/s]
100%|██████████| 3633/3633 [00:21<00:00, 165.59it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 68.85it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 247.56it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:02<00:00, 5462.97it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:13<00:00, 262.15it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:14<00:00, 251.68it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:02<00:00, 92.39it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 6530.51it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10892/10892 [00:00<00:00, 1223436.95it/s]
100%|██████████| 3633/3633 [00:22<00:00, 165.02it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 69.81it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:13<00:00, 262.29it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 5908.26it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:13<00:00, 260.89it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:14<00:00, 255.71it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:02<00:00, 92.31it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 7202.36it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11012/11012 [00:00<00:00, 29885.98it/s]
100%|██████████| 3633/3633 [00:21<00:00, 167.74it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 67.16it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:15<00:00, 240.11it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 5795.28it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 252.74it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:14<00:00, 249.05it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:03<00:00, 92.15it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 8394.50it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11141/11141 [00:00<00:00, 1117511.44it/s]
100%|██████████| 3633/3633 [00:21<00:00, 166.43it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 69.27it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 256.15it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 5918.67it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 256.19it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:15<00:00, 240.89it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:04<00:00, 91.35it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 8126.79it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11247/11247 [00:00<00:00, 1098919.96it/s]
100%|██████████| 3633/3633 [00:21<00:00, 165.45it/s]
tests in progress: 100%|██████████| 323/323 [00:05<00:00, 63.96it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:16<00:00, 223.41it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:02<00:00, 5172.26it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 243.66it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:15<00:00, 232.10it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:09<00:00, 87.52it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 7391.53it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11320/11320 [00:00<00:00, 698834.60it/s]
100%|██████████| 3633/3633 [00:22<00:00, 163.34it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 67.89it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 249.18it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 5952.94it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 251.20it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:14<00:00, 246.97it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [02:07<00:00, 89.04it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 8810.54it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11338/11338 [00:00<00:00, 910910.98it/s]
100%|██████████| 3633/3633 [00:22<00:00, 164.62it/s]
tests in progress: 100%|██████████| 323/323 [00:05<00:00, 63.66it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 249.91it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 6031.47it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:14<00:00, 242.84it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:15<00:00, 241.39it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:35<00:00, 119.07it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 14686.39it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<00:00, 14332.01it/s]
100%|██████████| 3633/3633 [00:14<00:00, 250.67it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 101.48it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 393.92it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8628.00it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 396.02it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 387.84it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:17<00:00, 145.57it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:02<00:00, 3919.14it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 5227/5227 [00:00<00:00, 1383892.63it/s]
100%|██████████| 3633/3633 [00:14<00:00, 255.15it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 117.55it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 385.86it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8376.87it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 387.72it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 384.00it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:22<00:00, 137.15it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 9486.85it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 8447/8447 [00:00<00:00, 883964.22it/s]
100%|██████████| 3633/3633 [00:15<00:00, 242.03it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 99.88it/s]

Best score so far: 0.32015
Best alpha: 0.5
Best thresh: 0.5

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 399.82it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8833.25it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 418.21it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 403.44it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:25<00:00, 132.69it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 12448.63it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10478/10478 [00:01<00:00, 9218.36it/s]
100%|██████████| 3633/3633 [00:13<00:00, 266.85it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 101.83it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 408.07it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8723.64it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 402.57it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 392.90it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:21<00:00, 139.65it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 12056.81it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10898/10898 [00:00<00:00, 1642278.05it/s]
100%|██████████| 3633/3633 [00:12<00:00, 279.68it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 96.08it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 425.89it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9545.79it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 425.72it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 405.41it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 140.65it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 13987.67it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11064/11064 [00:00<00:00, 1865859.01it/s]
100%|██████████| 3633/3633 [00:13<00:00, 271.70it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 96.01it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 427.85it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9611.69it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 429.40it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 409.39it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:21<00:00, 139.11it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 6200.56it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11181/11181 [00:00<00:00, 1877362.41it/s]
100%|██████████| 3633/3633 [00:13<00:00, 274.13it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 97.63it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 427.39it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9646.13it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 424.57it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 414.39it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 140.62it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 14070.06it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11267/11267 [00:00<00:00, 1256506.86it/s]
100%|██████████| 3633/3633 [00:13<00:00, 278.36it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 98.78it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 425.36it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8837.09it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 429.15it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 416.14it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:19<00:00, 141.93it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15638.33it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11330/11330 [00:00<00:00, 1848580.71it/s]
100%|██████████| 3633/3633 [00:12<00:00, 283.75it/s]
tests in progress: 100%|██████████| 323/323 [00:04<00:00, 75.73it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 420.38it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9686.49it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 429.44it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 417.28it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:21<00:00, 139.69it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 14008.51it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11339/11339 [00:00<00:00, 2168089.58it/s]
100%|██████████| 3633/3633 [00:14<00:00, 250.43it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 98.87it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 416.41it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8675.13it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 413.56it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 403.89it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 140.30it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 18036.64it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<00:00, 1439570.44it/s]
100%|██████████| 3633/3633 [00:12<00:00, 286.42it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 104.42it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 359.22it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9155.91it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 418.54it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 412.97it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 141.31it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:05<00:00, 1946.62it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 3280/3280 [00:00<00:00, 665247.44it/s]
100%|██████████| 3633/3633 [00:14<00:00, 247.08it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 119.40it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 429.01it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9619.44it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 414.17it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 411.81it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 141.42it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:02<00:00, 5007.89it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 6317/6317 [00:00<00:00, 1222733.78it/s]
100%|██████████| 3633/3633 [00:13<00:00, 272.63it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 113.22it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 426.17it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9148.85it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 413.34it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 419.50it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 140.75it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 11622.53it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 9273/9273 [00:00<00:00, 1789865.67it/s]
100%|██████████| 3633/3633 [00:13<00:00, 272.51it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 93.62it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 423.16it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9581.05it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 425.85it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 399.75it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 141.53it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 12496.11it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10791/10791 [00:00<00:00, 1557814.22it/s]
100%|██████████| 3633/3633 [00:13<00:00, 271.83it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 96.31it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 434.25it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9665.06it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 434.84it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 406.28it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:19<00:00, 142.63it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 14871.98it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11090/11090 [00:00<00:00, 1950716.35it/s]
100%|██████████| 3633/3633 [00:13<00:00, 273.08it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 95.68it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 428.41it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9251.29it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 431.69it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 420.49it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:19<00:00, 142.42it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15163.82it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11206/11206 [00:00<00:00, 28639.17it/s]
100%|██████████| 3633/3633 [00:12<00:00, 284.05it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 94.80it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 421.97it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9975.02it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 433.05it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 425.88it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 140.32it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 14278.80it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11279/11279 [00:00<00:00, 1796989.85it/s]
100%|██████████| 3633/3633 [00:14<00:00, 258.80it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 98.21it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 415.59it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8860.64it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 411.22it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 420.11it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 141.47it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15003.02it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11331/11331 [00:00<00:00, 1551908.92it/s]
100%|██████████| 3633/3633 [00:13<00:00, 277.36it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 94.27it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 427.62it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9413.76it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 422.48it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 418.67it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:20<00:00, 141.19it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15595.21it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11339/11339 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:12<00:00, 293.19it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 104.44it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 432.18it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8776.30it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 413.57it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 419.74it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:22<00:00, 137.23it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 12082.29it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<00:00, 885460.71it/s]
100%|██████████| 3633/3633 [00:19<00:00, 190.88it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 86.19it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 339.60it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7002.09it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 363.16it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 355.25it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:34<00:00, 119.69it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:07<00:00, 1487.54it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 1767/1767 [00:00<00:00, 518964.72it/s]
100%|██████████| 3633/3633 [00:18<00:00, 200.12it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 106.22it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 366.97it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 6886.00it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 361.67it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:10<00:00, 360.12it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:25<00:00, 132.64it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:04<00:00, 2426.12it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 4334/4334 [00:00<00:00, 687445.20it/s]
100%|██████████| 3633/3633 [00:14<00:00, 250.86it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 113.27it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 379.72it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8384.58it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 398.02it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 382.26it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:22<00:00, 137.09it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 5698.18it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 7313/7313 [00:00<00:00, 1932154.03it/s]
100%|██████████| 3633/3633 [00:14<00:00, 244.08it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 102.16it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 378.89it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8206.17it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 392.24it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 368.56it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:19<00:00, 143.14it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 12015.87it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 9889/9889 [00:01<00:00, 7675.46it/s]
100%|██████████| 3633/3633 [00:12<00:00, 282.21it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 103.85it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 434.00it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8950.52it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 429.52it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 418.88it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:26<00:00, 130.80it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 12875.59it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11054/11054 [00:00<00:00, 1733616.38it/s]
100%|██████████| 3633/3633 [00:13<00:00, 265.82it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 90.36it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 416.39it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8789.32it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 414.03it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 397.17it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:27<00:00, 130.10it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 14837.57it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11234/11234 [00:00<00:00, 1548483.72it/s]
100%|██████████| 3633/3633 [00:13<00:00, 264.56it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 90.23it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 414.80it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8762.73it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 410.35it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 387.67it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:15<00:00, 150.41it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15490.00it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11296/11296 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:12<00:00, 288.11it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 104.05it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 435.50it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9110.39it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 433.87it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 422.20it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:13<00:00, 153.50it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 16077.38it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11336/11336 [00:00<00:00, 1262556.90it/s]
100%|██████████| 3633/3633 [00:12<00:00, 292.16it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 109.90it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 442.52it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10213.36it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 440.43it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 429.33it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:14<00:00, 152.75it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15453.17it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11339/11339 [00:00<00:00, 22158.94it/s]
100%|██████████| 3633/3633 [00:12<00:00, 292.80it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 109.33it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 441.10it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10335.33it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 439.28it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 427.65it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:13<00:00, 153.36it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 17759.61it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<00:00, 2581880.76it/s]
100%|██████████| 3633/3633 [00:12<00:00, 297.24it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 109.99it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 441.68it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10471.28it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 441.27it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 431.19it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:13<00:00, 155.27it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:07<00:00, 1503.04it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 859/859 [00:00<00:00, 294234.96it/s]
100%|██████████| 3633/3633 [00:13<00:00, 271.22it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 141.82it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 439.96it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10435.19it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 440.29it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 431.00it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:13<00:00, 155.18it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:05<00:00, 2170.01it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 2701/2701 [00:00<00:00, 268334.52it/s]
100%|██████████| 3633/3633 [00:13<00:00, 277.01it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 130.00it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 441.44it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9814.61it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 441.96it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 428.83it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:12<00:00, 155.36it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:03<00:00, 3660.86it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 5358/5358 [00:00<00:00, 1610050.21it/s]
100%|██████████| 3633/3633 [00:14<00:00, 255.86it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 123.53it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 437.96it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10060.55it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 436.56it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 426.91it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:15<00:00, 149.28it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 8647.69it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 8240/8240 [00:00<00:00, 966148.52it/s]
100%|██████████| 3633/3633 [00:13<00:00, 271.47it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 96.84it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 430.48it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9283.96it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 437.32it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 432.53it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:13<00:00, 153.60it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 6614.04it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10360/10360 [00:00<00:00, 2698273.07it/s]
100%|██████████| 3633/3633 [00:12<00:00, 282.49it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 81.69it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 400.42it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9536.46it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 433.49it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 421.58it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:15<00:00, 151.12it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 13027.63it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11218/11218 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:12<00:00, 287.00it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 99.15it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 425.98it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9974.96it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 447.00it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 434.07it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:16<00:00, 148.94it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15282.93it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11308/11308 [00:00<00:00, 12647.52it/s]
100%|██████████| 3633/3633 [00:12<00:00, 287.68it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 104.03it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 440.95it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9522.80it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 432.59it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 408.49it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:16<00:00, 148.05it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 16238.19it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11337/11337 [00:00<00:00, 1106708.20it/s]
100%|██████████| 3633/3633 [00:13<00:00, 260.67it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 90.03it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 401.90it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9431.20it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 423.60it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 417.99it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:16<00:00, 148.52it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15749.80it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11339/11339 [00:00<00:00, 3714402.77it/s]
100%|██████████| 3633/3633 [00:12<00:00, 302.18it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 108.60it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 437.04it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9772.04it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 431.82it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 422.70it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:18<00:00, 144.69it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 16891.91it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<00:00, 1889761.51it/s]
100%|██████████| 3633/3633 [00:13<00:00, 278.07it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 109.03it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 420.63it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10029.43it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 443.79it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 433.77it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:15<00:00, 150.80it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:09<00:00, 1253.86it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 370/370 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:13<00:00, 267.76it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 142.06it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 429.56it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9803.27it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 429.32it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 418.13it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:17<00:00, 146.53it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:06<00:00, 1633.61it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 1483/1483 [00:00<00:00, 742882.22it/s]
100%|██████████| 3633/3633 [00:14<00:00, 257.56it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 145.86it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 435.16it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9337.12it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 408.58it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 409.50it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:21<00:00, 138.69it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:04<00:00, 2450.88it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 3685/3685 [00:01<00:00, 3559.39it/s]
100%|██████████| 3633/3633 [00:13<00:00, 269.99it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 137.86it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 439.26it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9430.51it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 438.24it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 419.62it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:16<00:00, 148.76it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:02<00:00, 4943.09it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 6339/6339 [00:00<00:00, 9577699.23it/s]
100%|██████████| 3633/3633 [00:12<00:00, 292.69it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 121.30it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 431.19it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9001.72it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 415.09it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 432.45it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:12<00:00, 156.78it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 9652.24it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 8956/8956 [00:00<00:00, 1055618.56it/s]
100%|██████████| 3633/3633 [00:13<00:00, 279.37it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 105.70it/s]

Best score so far: 0.3207
Best alpha: 0.6666666666666666
Best thresh: 0.6666666666666666

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 422.63it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9929.27it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 424.09it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 430.50it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:12<00:00, 157.15it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 7770.80it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10713/10713 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:12<00:00, 299.36it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 106.10it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 437.04it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9944.97it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 432.17it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 421.42it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:16<00:00, 147.39it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 14410.38it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11311/11311 [00:00<00:00, 723197.75it/s]
100%|██████████| 3633/3633 [00:12<00:00, 293.00it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 110.28it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 427.48it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10539.74it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 437.31it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 431.50it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:18<00:00, 143.72it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15890.50it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11338/11338 [00:00<00:00, 15503.53it/s]
100%|██████████| 3633/3633 [00:12<00:00, 283.23it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 105.37it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 432.34it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9904.05it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 432.67it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 416.07it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:17<00:00, 146.02it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 14822.15it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11339/11339 [00:00<00:00, 1781110.52it/s]
100%|██████████| 3633/3633 [00:12<00:00, 283.93it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 101.61it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 421.74it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7970.53it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:10<00:00, 337.55it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 400.45it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:17<00:00, 145.48it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 16743.99it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<00:00, 1569594.01it/s]
100%|██████████| 3633/3633 [00:12<00:00, 289.41it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 102.21it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 438.98it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10121.84it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 436.28it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 422.12it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:13<00:00, 155.15it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:11<00:00, 1011.86it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 160/160 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:13<00:00, 275.50it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 152.37it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 443.95it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10338.73it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 444.29it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 429.74it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:14<00:00, 151.39it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:08<00:00, 1392.72it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 746/746 [00:00<00:00, 211801.99it/s]
100%|██████████| 3633/3633 [00:14<00:00, 259.04it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 137.68it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 417.09it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9192.34it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 432.99it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 417.25it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:15<00:00, 150.39it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:05<00:00, 1960.82it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 2260/2260 [00:00<00:00, 1178849.28it/s]
100%|██████████| 3633/3633 [00:13<00:00, 275.84it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 148.16it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 429.02it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9698.59it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 425.08it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 421.28it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:15<00:00, 150.78it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:03<00:00, 2903.07it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 4602/4602 [00:00<00:00, 895028.61it/s]
100%|██████████| 3633/3633 [00:13<00:00, 267.22it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 127.95it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 423.41it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10036.98it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 434.29it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:09<00:00, 399.40it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:15<00:00, 150.71it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 5807.79it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 7195/7195 [00:00<00:00, 3002190.34it/s]
100%|██████████| 3633/3633 [00:12<00:00, 286.82it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 116.84it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 426.83it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9694.08it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 430.30it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 420.47it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:17<00:00, 146.88it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 10657.82it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 9489/9489 [00:00<00:00, 1577915.02it/s]
100%|██████████| 3633/3633 [00:12<00:00, 284.86it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 110.19it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 426.16it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9577.86it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 414.46it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 416.18it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:17<00:00, 147.23it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 13724.24it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 10932/10932 [00:00<00:00, 855210.88it/s]
100%|██████████| 3633/3633 [00:12<00:00, 281.67it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 108.88it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 442.20it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9540.40it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 444.97it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 438.06it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:13<00:00, 154.47it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15544.13it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11332/11332 [00:00<00:00, 1321338.10it/s]
100%|██████████| 3633/3633 [00:12<00:00, 294.70it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 109.18it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 433.73it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9925.21it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 448.48it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 437.79it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:19<00:00, 142.16it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15177.51it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11339/11339 [00:00<00:00, 654103.52it/s]
100%|██████████| 3633/3633 [00:12<00:00, 287.08it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 107.69it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 442.45it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10699.65it/s]
Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 447.35it/s]
Getting word presence: 100%|██████████| 3633/3633 [00:08<00:00, 431.62it/s]
Calculating coexistence probability: 100%|██████████| 11340/11340 [01:14<00:00, 152.86it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15713.18it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:11<00:00, 306.23it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 112.51it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 436.93it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9165.36it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:10<00:00, 1060.38it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 77/77 [00:00<00:00, 36230.81it/s]
100%|██████████| 3633/3633 [00:14<00:00, 258.02it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 137.18it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 426.19it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10299.55it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:09<00:00, 1224.82it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 365/365 [00:00<00:00, 467028.97it/s]
100%|██████████| 3633/3633 [00:14<00:00, 258.75it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 149.70it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 438.93it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10031.99it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:07<00:00, 1545.86it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 1282/1282 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:13<00:00, 277.48it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 152.01it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 432.40it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9421.14it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:05<00:00, 2109.81it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 3123/3123 [00:00<00:00, 1265952.58it/s]
100%|██████████| 3633/3633 [00:13<00:00, 267.03it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 144.27it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 438.22it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 9737.02it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:03<00:00, 3755.29it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 5449/5449 [00:00<00:00, 348576.43it/s]
100%|██████████| 3633/3633 [00:13<00:00, 261.35it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 126.85it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 398.97it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 6271.85it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:02<00:00, 5222.54it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 7948/7948 [00:00<00:00, 1759358.68it/s]
100%|██████████| 3633/3633 [00:18<00:00, 201.19it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 96.60it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 379.72it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 7784.24it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:01<00:00, 7824.17it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 9908/9908 [00:00<00:00, 1695242.07it/s]
100%|██████████| 3633/3633 [00:15<00:00, 236.77it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 96.76it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:09<00:00, 388.07it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 6379.33it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 11746.80it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11072/11072 [00:00<00:00, 891127.62it/s]
100%|██████████| 3633/3633 [00:15<00:00, 241.44it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 97.37it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 404.12it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 8023.67it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 15403.16it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11337/11337 [00:00<00:00, 4586748.77it/s]
100%|██████████| 3633/3633 [00:13<00:00, 275.06it/s]
tests in progress: 100%|██████████| 323/323 [00:03<00:00, 95.89it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888

Getting unique words: 100%|██████████| 3633/3633 [00:08<00:00, 442.18it/s]

Normalizing embeddings for cosine similarity...
Embeddings normalized.
Creating Faiss index...
Faiss index created.
getting distances
end of getting distances

filling similarity matrix: 100%|██████████| 11340/11340 [00:01<00:00, 10730.57it/s]
Getting replaceable words: 100%|██████████| 11340/11340 [00:00<00:00, 18444.59it/s]

finding graph components...
graph components found

Creating clusters dict: 100%|██████████| 11340/11340 [00:00<?, ?it/s]
100%|██████████| 3633/3633 [00:12<00:00, 289.13it/s]
tests in progress: 100%|██████████| 323/323 [00:02<00:00, 113.61it/s]

Best score so far: 0.32166
Best alpha: 0.8888888888888888
Best thresh: 0.8888888888888888